/* ==========================================================
   Alpine Draft Room - player data
   GENERATED FILE. Edit scripts/build_players.py instead.

   Generated : 2026-08-04 13:04 UTC
   Players   : 203
   Matched   : 203 carry a Sleeper id
   Flagged   : 14 carry an injury designation
   Projected : 203 have 2026 projections

   ADP: Fantasy Football Calculator, 10-team half PPR.
   Player, injury and stat data: Sleeper.
   ========================================================== */

const PLAYERS_META = { generated: "2026-08-04 13:04 UTC", count: 203, matched: 203, flagged: 14, projected: 203, unmatched: 0 };

const PLAYERS = [
  { id: "9221", name: "Jahmyr Gibbs", pos: "RB", team: "DET", bye: 6, adp: 1.5, inj: "Q" },
  { id: "9509", name: "Bijan Robinson", pos: "RB", team: "ATL", bye: 11, adp: 2.1, inj: "" },
  { id: "9493", name: "Puka Nacua", pos: "WR", team: "LAR", bye: 11, adp: 2.5, inj: "" },
  { id: "7564", name: "Ja'Marr Chase", pos: "WR", team: "CIN", bye: 6, adp: 4.0, inj: "" },
  { id: "9488", name: "Jaxon Smith-Njigba", pos: "WR", team: "SEA", bye: 11, adp: 5.1, inj: "" },
  { id: "4034", name: "Christian McCaffrey", pos: "RB", team: "SF", bye: 8, adp: 5.7, inj: "" },
  { id: "6813", name: "Jonathan Taylor", pos: "RB", team: "IND", bye: 13, adp: 6.4, inj: "" },
  { id: "7547", name: "Amon-Ra St. Brown", pos: "WR", team: "DET", bye: 6, adp: 7.8, inj: "" },
  { id: "9226", name: "De'Von Achane", pos: "RB", team: "MIA", bye: 6, adp: 9.2, inj: "" },
  { id: "8112", name: "Drake London", pos: "WR", team: "ATL", bye: 11, adp: 10.4, inj: "" },
  { id: "8138", name: "James Cook III", pos: "RB", team: "BUF", bye: 7, adp: 10.7, inj: "" },
  { id: "3198", name: "Derrick Henry", pos: "RB", team: "BAL", bye: 13, adp: 10.9, inj: "" },
  { id: "10229", name: "Rashee Rice", pos: "WR", team: "KC", bye: 5, adp: 13.2, inj: "" },
  { id: "6786", name: "CeeDee Lamb", pos: "WR", team: "DAL", bye: 14, adp: 13.6, inj: "" },
  { id: "6794", name: "Justin Jefferson", pos: "WR", team: "MIN", bye: 6, adp: 14.3, inj: "" },
  { id: "12527", name: "Ashton Jeanty", pos: "RB", team: "LV", bye: 13, adp: 15.0, inj: "" },
  { id: "9224", name: "Chase Brown", pos: "RB", team: "CIN", bye: 6, adp: 16.8, inj: "" },
  { id: "4866", name: "Saquon Barkley", pos: "RB", team: "PHI", bye: 10, adp: 17.2, inj: "" },
  { id: "5859", name: "A.J. Brown", pos: "WR", team: "NE", bye: 11, adp: 18.8, inj: "" },
  { id: "8137", name: "George Pickens", pos: "WR", team: "DAL", bye: 14, adp: 21.0, inj: "" },
  { id: "12507", name: "Omarion Hampton", pos: "RB", team: "LAC", bye: 7, adp: 21.3, inj: "" },
  { id: "5850", name: "Josh Jacobs", pos: "RB", team: "GB", bye: 11, adp: 21.3, inj: "" },
  { id: "8144", name: "Chris Olave", pos: "WR", team: "NO", bye: 8, adp: 22.7, inj: "" },
  { id: "7569", name: "Nico Collins", pos: "WR", team: "HOU", bye: 8, adp: 23.0, inj: "" },
  { id: "9997", name: "Zay Flowers", pos: "WR", team: "BAL", bye: 13, adp: 25.8, inj: "" },
  { id: "8155", name: "Breece Hall", pos: "RB", team: "NYJ", bye: 13, adp: 25.8, inj: "" },
  { id: "8151", name: "Kenneth Walker III", pos: "RB", team: "KC", bye: 5, adp: 25.8, inj: "" },
  { id: "4984", name: "Josh Allen", pos: "QB", team: "BUF", bye: 7, adp: 25.8, inj: "" },
  { id: "13287", name: "Jeremiyah Love", pos: "RB", team: "ARI", bye: 14, adp: 27.0, inj: "" },
  { id: "8146", name: "Garrett Wilson", pos: "WR", team: "NYJ", bye: 13, adp: 29.9, inj: "" },
  { id: "8150", name: "Kyren Williams", pos: "RB", team: "LAR", bye: 11, adp: 31.3, inj: "" },
  { id: "12481", name: "Cam Skattebo", pos: "RB", team: "NYG", bye: 8, adp: 32.4, inj: "" },
  { id: "7525", name: "DeVonta Smith", pos: "WR", team: "PHI", bye: 10, adp: 32.5, inj: "" },
  { id: "12514", name: "Emeka Egbuka", pos: "WR", team: "TB", bye: 10, adp: 32.7, inj: "" },
  { id: "7588", name: "Javonte Williams", pos: "RB", team: "DAL", bye: 14, adp: 35.4, inj: "" },
  { id: "11632", name: "Malik Nabers", pos: "WR", team: "NYG", bye: 8, adp: 35.7, inj: "Q" },
  { id: "12526", name: "Tetairoa McMillan", pos: "WR", team: "CAR", bye: 5, adp: 36.2, inj: "" },
  { id: "6801", name: "Tee Higgins", pos: "WR", team: "CIN", bye: 6, adp: 38.1, inj: "" },
  { id: "7543", name: "Travis Etienne Jr.", pos: "RB", team: "NO", bye: 8, adp: 38.7, inj: "" },
  { id: "2133", name: "Davante Adams", pos: "WR", team: "LAR", bye: 11, adp: 39.9, inj: "" },
  { id: "11584", name: "Bucky Irving", pos: "RB", team: "TB", bye: 10, adp: 40.2, inj: "" },
  { id: "8148", name: "Jameson Williams", pos: "WR", team: "DET", bye: 6, adp: 42.3, inj: "" },
  { id: "5927", name: "Terry McLaurin", pos: "WR", team: "WAS", bye: 7, adp: 42.6, inj: "" },
  { id: "8130", name: "Trey McBride", pos: "TE", team: "ARI", bye: 14, adp: 42.8, inj: "" },
  { id: "6790", name: "D'Andre Swift", pos: "RB", team: "CHI", bye: 10, adp: 43.3, inj: "" },
  { id: "11620", name: "Rome Odunze", pos: "WR", team: "CHI", bye: 10, adp: 44.0, inj: "" },
  { id: "11604", name: "Brock Bowers", pos: "TE", team: "LV", bye: 13, adp: 45.8, inj: "" },
  { id: "12512", name: "Quinshon Judkins", pos: "RB", team: "CLE", bye: 11, adp: 46.9, inj: "" },
  { id: "8142", name: "Alec Pierce", pos: "WR", team: "IND", bye: 13, adp: 47.6, inj: "PUP" },
  { id: "11635", name: "Ladd McConkey", pos: "WR", team: "LAC", bye: 7, adp: 48.2, inj: "" },
  { id: "11564", name: "Drake Maye", pos: "QB", team: "NE", bye: 11, adp: 48.3, inj: "" },
  { id: "4983", name: "DJ Moore", pos: "WR", team: "BUF", bye: 7, adp: 48.8, inj: "" },
  { id: "12490", name: "Bhayshul Tuten", pos: "RB", team: "JAX", bye: 7, adp: 50.1, inj: "" },
  { id: "7526", name: "Jaylen Waddle", pos: "WR", team: "DEN", bye: 10, adp: 51.4, inj: "" },
  { id: "4881", name: "Lamar Jackson", pos: "QB", team: "BAL", bye: 13, adp: 53.9, inj: "" },
  { id: "12519", name: "Luther Burden III", pos: "WR", team: "CHI", bye: 10, adp: 54.5, inj: "" },
  { id: "6770", name: "Joe Burrow", pos: "QB", team: "CIN", bye: 6, adp: 54.9, inj: "" },
  { id: "12529", name: "TreVeyon Henderson", pos: "RB", team: "NE", bye: 11, adp: 56.0, inj: "" },
  { id: "13286", name: "Jadarian Price", pos: "RB", team: "SEA", bye: 11, adp: 58.7, inj: "" },
  { id: "5045", name: "Courtland Sutton", pos: "WR", team: "DEN", bye: 10, adp: 59.1, inj: "" },
  { id: "2216", name: "Mike Evans", pos: "WR", team: "SF", bye: 8, adp: 61.0, inj: "Q" },
  { id: "5892", name: "David Montgomery", pos: "RB", team: "HOU", bye: 8, adp: 61.6, inj: "" },
  { id: "11628", name: "Marvin Harrison Jr.", pos: "WR", team: "ARI", bye: 14, adp: 62.6, inj: "" },
  { id: "8167", name: "Christian Watson", pos: "WR", team: "GB", bye: 11, adp: 63.8, inj: "" },
  { id: "5846", name: "DK Metcalf", pos: "WR", team: "PIT", bye: 9, adp: 64.8, inj: "" },
  { id: "12517", name: "Colston Loveland", pos: "TE", team: "CHI", bye: 10, adp: 64.9, inj: "" },
  { id: "3294", name: "Dak Prescott", pos: "QB", team: "DAL", bye: 14, adp: 65.9, inj: "" },
  { id: "5967", name: "Tony Pollard", pos: "RB", team: "TEN", bye: 9, adp: 66.5, inj: "" },
  { id: "11566", name: "Jayden Daniels", pos: "QB", team: "WAS", bye: 7, adp: 68.7, inj: "" },
  { id: "12518", name: "Tyler Warren", pos: "TE", team: "IND", bye: 13, adp: 69.6, inj: "" },
  { id: "9487", name: "Parker Washington", pos: "WR", team: "JAX", bye: 7, adp: 71.6, inj: "" },
  { id: "7021", name: "Rico Dowdle", pos: "RB", team: "PIT", bye: 9, adp: 71.8, inj: "" },
  { id: "5947", name: "Jakobi Meyers", pos: "WR", team: "JAX", bye: 7, adp: 72.9, inj: "" },
  { id: "7611", name: "Rhamondre Stevenson", pos: "RB", team: "NE", bye: 11, adp: 73.2, inj: "" },
  { id: "13279", name: "Carnell Tate", pos: "WR", team: "TEN", bye: 9, adp: 73.6, inj: "" },
  { id: "6904", name: "Jalen Hurts", pos: "QB", team: "PHI", bye: 10, adp: 73.9, inj: "" },
  { id: "7594", name: "Chuba Hubbard", pos: "RB", team: "CAR", bye: 5, adp: 75.7, inj: "" },
  { id: "8228", name: "Jaylen Warren", pos: "RB", team: "PIT", bye: 9, adp: 76.1, inj: "" },
  { id: "11631", name: "Brian Thomas Jr.", pos: "WR", team: "JAX", bye: 7, adp: 76.8, inj: "" },
  { id: "6819", name: "Michael Pittman Jr.", pos: "WR", team: "PIT", bye: 9, adp: 77.8, inj: "" },
  { id: "8126", name: "Wan'Dale Robinson", pos: "WR", team: "TEN", bye: 9, adp: 78.5, inj: "" },
  { id: "8183", name: "Brock Purdy", pos: "QB", team: "SF", bye: 8, adp: 78.7, inj: "" },
  { id: "7553", name: "Kyle Pitts Sr.", pos: "TE", team: "ATL", bye: 11, adp: 80.2, inj: "" },
  { id: "421", name: "Matthew Stafford", pos: "QB", team: "LAR", bye: 11, adp: 80.8, inj: "" },
  { id: "12506", name: "Harold Fannin Jr.", pos: "TE", team: "CLE", bye: 11, adp: 81.5, inj: "" },
  { id: "9754", name: "Quentin Johnston", pos: "WR", team: "LAC", bye: 7, adp: 83.7, inj: "" },
  { id: "6806", name: "J.K. Dobbins", pos: "RB", team: "DEN", bye: 10, adp: 83.8, inj: "" },
  { id: "13281", name: "Jordyn Tyson", pos: "WR", team: "NO", bye: 8, adp: 84.5, inj: "" },
  { id: "10222", name: "Jayden Reed", pos: "WR", team: "GB", bye: 11, adp: 86.9, inj: "" },
  { id: "9756", name: "Jordan Addison", pos: "WR", team: "MIN", bye: 6, adp: 87.3, inj: "" },
  { id: "4037", name: "Chris Godwin Jr.", pos: "WR", team: "TB", bye: 10, adp: 88.1, inj: "" },
  { id: "7523", name: "Trevor Lawrence", pos: "QB", team: "JAX", bye: 7, adp: 88.6, inj: "" },
  { id: "10232", name: "Michael Wilson", pos: "WR", team: "ARI", bye: 14, adp: 89.5, inj: "" },
  { id: "4199", name: "Aaron Jones Sr.", pos: "RB", team: "MIN", bye: 6, adp: 89.9, inj: "" },
  { id: "12489", name: "RJ Harvey", pos: "RB", team: "DEN", bye: 10, adp: 90.6, inj: "" },
  { id: "DEN", name: "Denver Defense", pos: "DST", team: "DEN", bye: 10, adp: 91.6, inj: "" },
  { id: "10859", name: "Sam LaPorta", pos: "TE", team: "DET", bye: 6, adp: 94.7, inj: "" },
  { id: "11624", name: "Xavier Worthy", pos: "WR", team: "KC", bye: 5, adp: 95.6, inj: "Q" },
  { id: "12534", name: "Kyle Monangai", pos: "RB", team: "CHI", bye: 10, adp: 98.5, inj: "" },
  { id: "5872", name: "Deebo Samuel Sr.", pos: "WR", team: "SF", bye: 8, adp: 98.6, inj: "" },
  { id: "5022", name: "Dallas Goedert", pos: "TE", team: "PHI", bye: 10, adp: 98.8, inj: "" },
  { id: "4046", name: "Patrick Mahomes", pos: "QB", team: "KC", bye: 5, adp: 99.7, inj: "Q" },
  { id: "13294", name: "Makai Lemon", pos: "WR", team: "PHI", bye: 10, adp: 100.1, inj: "Q" },
  { id: "8136", name: "Rachaad White", pos: "RB", team: "WAS", bye: 7, adp: 100.9, inj: "" },
  { id: "8134", name: "Khalil Shakir", pos: "WR", team: "BUF", bye: 7, adp: 101.2, inj: "" },
  { id: "SEA", name: "Seattle Defense", pos: "DST", team: "SEA", bye: 11, adp: 102.2, inj: "" },
  { id: "7567", name: "Kenny Gainwell", pos: "RB", team: "TB", bye: 10, adp: 102.6, inj: "" },
  { id: "9500", name: "Josh Downs", pos: "WR", team: "IND", bye: 13, adp: 102.6, inj: "" },
  { id: "8121", name: "Romeo Doubs", pos: "WR", team: "NE", bye: 11, adp: 103.7, inj: "" },
  { id: "8676", name: "Rashid Shaheed", pos: "WR", team: "SEA", bye: 11, adp: 104.5, inj: "" },
  { id: "11560", name: "Caleb Williams", pos: "QB", team: "CHI", bye: 10, adp: 105.3, inj: "" },
  { id: "12508", name: "Jaxson Dart", pos: "QB", team: "NYG", bye: 8, adp: 107.1, inj: "" },
  { id: "6797", name: "Justin Herbert", pos: "QB", team: "LAC", bye: 7, adp: 108.4, inj: "" },
  { id: "12501", name: "Matthew Golden", pos: "WR", team: "GB", bye: 11, adp: 108.8, inj: "" },
  { id: "3163", name: "Jared Goff", pos: "QB", team: "DET", bye: 6, adp: 109.1, inj: "" },
  { id: "HOU", name: "Houston Defense", pos: "DST", team: "HOU", bye: 8, adp: 109.3, inj: "" },
  { id: "12533", name: "Jacory Croskey-Merritt", pos: "RB", team: "WAS", bye: 7, adp: 109.5, inj: "" },
  { id: "11638", name: "Ricky Pearsall", pos: "WR", team: "SF", bye: 8, adp: 110.7, inj: "IR" },
  { id: "MIN", name: "Minnesota Defense", pos: "DST", team: "MIN", bye: 6, adp: 111.2, inj: "" },
  { id: "9484", name: "Tucker Kraft", pos: "TE", team: "GB", bye: 11, adp: 112.1, inj: "Q" },
  { id: "1466", name: "Travis Kelce", pos: "TE", team: "KC", bye: 5, adp: 114.0, inj: "" },
  { id: "11586", name: "Blake Corum", pos: "RB", team: "LAR", bye: 11, adp: 114.2, inj: "" },
  { id: "8147", name: "John Metchie III", pos: "WR", team: "CAR", bye: 5, adp: 116.9, inj: "" },
  { id: "4981", name: "Calvin Ridley", pos: "WR", team: "TEN", bye: 9, adp: 117.5, inj: "" },
  { id: "11563", name: "Bo Nix", pos: "QB", team: "DEN", bye: 10, adp: 118.4, inj: "" },
  { id: "DET", name: "Detroit Defense", pos: "DST", team: "DET", bye: 6, adp: 118.5, inj: "" },
  { id: "8408", name: "Jordan Mason", pos: "RB", team: "MIN", bye: 6, adp: 119.2, inj: "" },
  { id: "11646", name: "Jalen Coker", pos: "WR", team: "CAR", bye: 5, adp: 121.4, inj: "" },
  { id: "11583", name: "Jonathon Brooks", pos: "RB", team: "CAR", bye: 5, adp: 122.9, inj: "" },
  { id: "2747", name: "Jason Myers", pos: "K", team: "SEA", bye: 11, adp: 124.4, inj: "" },
  { id: "13298", name: "KC Concepcion", pos: "WR", team: "CLE", bye: 11, adp: 126.4, inj: "Q" },
  { id: "11533", name: "Brandon Aubrey", pos: "K", team: "DAL", bye: 14, adp: 126.5, inj: "" },
  { id: "5012", name: "Mark Andrews", pos: "TE", team: "BAL", bye: 13, adp: 127.5, inj: "" },
  { id: "12860", name: "Theo Wease Jr.", pos: "WR", team: "MIA", bye: 6, adp: 128.3, inj: "" },
  { id: "9753", name: "Zach Charbonnet", pos: "RB", team: "SEA", bye: 11, adp: 129.7, inj: "PUP" },
  { id: "4217", name: "George Kittle", pos: "TE", team: "SF", bye: 8, adp: 132.5, inj: "PUP" },
  { id: "7571", name: "Rashod Bateman", pos: "WR", team: "BAL", bye: 13, adp: 132.7, inj: "" },
  { id: "4892", name: "Baker Mayfield", pos: "QB", team: "TB", bye: 10, adp: 133.4, inj: "" },
  { id: "8698", name: "Jake Tonges", pos: "TE", team: "SF", bye: 8, adp: 133.4, inj: "" },
  { id: "10213", name: "Tre Tucker", pos: "WR", team: "LV", bye: 13, adp: 133.7, inj: "" },
  { id: "8180", name: "Jalen Nailor", pos: "WR", team: "LV", bye: 13, adp: 134.5, inj: "" },
  { id: "12484", name: "Jayden Higgins", pos: "WR", team: "HOU", bye: 8, adp: 134.8, inj: "" },
  { id: "6783", name: "Jerry Jeudy", pos: "WR", team: "CLE", bye: 11, adp: 135.0, inj: "" },
  { id: "7049", name: "Jauan Jennings", pos: "WR", team: "MIN", bye: 6, adp: 135.0, inj: "" },
  { id: "3451", name: "Ka'imi Fairbairn", pos: "K", team: "HOU", bye: 8, adp: 135.4, inj: "" },
  { id: "8131", name: "Isaiah Likely", pos: "TE", team: "NYG", bye: 8, adp: 136.2, inj: "" },
  { id: "12545", name: "Tyler Shough", pos: "QB", team: "NO", bye: 8, adp: 136.6, inj: "" },
  { id: "NE", name: "New England Defense", pos: "DST", team: "NE", bye: 11, adp: 138.3, inj: "" },
  { id: "11539", name: "Jake Bates", pos: "K", team: "DET", bye: 6, adp: 139.0, inj: "" },
  { id: "9508", name: "Tyjae Spears", pos: "RB", team: "TEN", bye: 9, adp: 139.6, inj: "" },
  { id: "4943", name: "Sam Darnold", pos: "QB", team: "SEA", bye: 11, adp: 139.7, inj: "" },
  { id: "LAR", name: "LA Rams Defense", pos: "DST", team: "LAR", bye: 11, adp: 139.7, inj: "" },
  { id: "11618", name: "Jalen McMillan", pos: "WR", team: "TB", bye: 10, adp: 139.9, inj: "" },
  { id: "3214", name: "Hunter Henry", pos: "TE", team: "NE", bye: 11, adp: 141.6, inj: "" },
  { id: "5189", name: "Eddy Piñeiro", pos: "K", team: "SF", bye: 8, adp: 142.4, inj: "" },
  { id: "4035", name: "Alvin Kamara", pos: "RB", team: "NO", bye: 8, adp: 142.6, inj: "" },
  { id: "13301", name: "Antonio Williams", pos: "WR", team: "WAS", bye: 7, adp: 143.3, inj: "" },
  { id: "8205", name: "Isiah Pacheco", pos: "RB", team: "DET", bye: 6, adp: 143.5, inj: "" },
  { id: "12474", name: "Woody Marks", pos: "RB", team: "HOU", bye: 8, adp: 143.7, inj: "" },
  { id: "8259", name: "Cameron Dicker", pos: "K", team: "LAC", bye: 7, adp: 143.9, inj: "" },
  { id: "5849", name: "Kyler Murray", pos: "QB", team: "MIN", bye: 6, adp: 144.5, inj: "" },
  { id: "PHI", name: "Philadelphia Defense", pos: "DST", team: "PHI", bye: 10, adp: 144.6, inj: "" },
  { id: "9502", name: "Tank Dell", pos: "WR", team: "HOU", bye: 8, adp: 144.8, inj: "Q" },
  { id: "LAC", name: "LA Chargers Defense", pos: "DST", team: "LAC", bye: 7, adp: 145.4, inj: "" },
  { id: "12015", name: "Harrison Mevis", pos: "K", team: "LAR", bye: 11, adp: 145.9, inj: "" },
  { id: "6804", name: "Jordan Love", pos: "QB", team: "GB", bye: 11, adp: 146.0, inj: "" },
  { id: "8154", name: "Brian Robinson Jr.", pos: "RB", team: "ATL", bye: 11, adp: 146.3, inj: "" },
  { id: "9504", name: "Kayshon Boutte", pos: "WR", team: "NE", bye: 11, adp: 146.9, inj: "" },
  { id: "2020", name: "Cairo Santos", pos: "K", team: "CHI", bye: 10, adp: 148.9, inj: "" },
  { id: "12711", name: "Tyler Loop", pos: "K", team: "BAL", bye: 13, adp: 150.2, inj: "" },
  { id: "10236", name: "Dalton Kincaid", pos: "TE", team: "BUF", bye: 7, adp: 150.9, inj: "" },
  { id: "6650", name: "Chase McLaughlin", pos: "K", team: "TB", bye: 10, adp: 152.3, inj: "" },
  { id: "9225", name: "Tank Bigsby", pos: "RB", team: "PHI", bye: 10, adp: 152.4, inj: "" },
  { id: "4039", name: "Cooper Kupp", pos: "WR", team: "SEA", bye: 11, adp: 152.5, inj: "" },
  { id: "9480", name: "Brenton Strange", pos: "TE", team: "JAX", bye: 7, adp: 154.1, inj: "" },
  { id: "13346", name: "Denzel Boston", pos: "WR", team: "CLE", bye: 11, adp: 154.2, inj: "" },
  { id: "11655", name: "Tyrone Tracy Jr.", pos: "RB", team: "NYG", bye: 8, adp: 155.8, inj: "" },
  { id: "8110", name: "Jake Ferguson", pos: "TE", team: "DAL", bye: 14, adp: 156.3, inj: "" },
  { id: "11792", name: "Will Reichard", pos: "K", team: "MIN", bye: 6, adp: 156.7, inj: "" },
  { id: "9511", name: "Keaton Mitchell", pos: "RB", team: "LAC", bye: 7, adp: 157.2, inj: "" },
  { id: "8161", name: "Malik Willis", pos: "QB", team: "MIA", bye: 6, adp: 157.6, inj: "" },
  { id: "4227", name: "Harrison Butker", pos: "K", team: "KC", bye: 5, adp: 157.6, inj: "" },
  { id: "PIT", name: "Pittsburgh Defense", pos: "DST", team: "PIT", bye: 9, adp: 158.9, inj: "" },
  { id: "13276", name: "Omar Cooper Jr.", pos: "WR", team: "NYJ", bye: 13, adp: 159.1, inj: "" },
  { id: "12530", name: "Travis Hunter", pos: "WR", team: "JAX", bye: 7, adp: 159.5, inj: "" },
  { id: "8132", name: "Tyler Allgeier", pos: "RB", team: "ARI", bye: 14, adp: 159.6, inj: "" },
  { id: "7042", name: "Tyler Bass", pos: "K", team: "BUF", bye: 7, adp: 160.1, inj: "" },
  { id: "BUF", name: "Buffalo Defense", pos: "DST", team: "BUF", bye: 7, adp: 160.5, inj: "" },
  { id: "7002", name: "Juwan Johnson", pos: "TE", team: "NO", bye: 8, adp: 160.8, inj: "" },
  { id: "11625", name: "Adonai Mitchell", pos: "WR", team: "NYJ", bye: 13, adp: 161.5, inj: "" },
  { id: "7839", name: "Evan McPherson", pos: "K", team: "CIN", bye: 6, adp: 163.0, inj: "" },
  { id: "13330", name: "Kenyon Sadiq", pos: "TE", team: "NYJ", bye: 13, adp: 163.2, inj: "" },
  { id: "11786", name: "Cam Little", pos: "K", team: "JAX", bye: 7, adp: 163.9, inj: "" },
  { id: "TEN", name: "Tennessee Defense", pos: "DST", team: "TEN", bye: 9, adp: 165.0, inj: "" },
  { id: "13417", name: "De'Zhaun Stribling", pos: "WR", team: "SF", bye: 8, adp: 165.0, inj: "Q" },
  { id: "1945", name: "Chris Boswell", pos: "K", team: "PIT", bye: 9, adp: 166.0, inj: "" },
  { id: "13305", name: "Mike Washington Jr.", pos: "RB", team: "LV", bye: 13, adp: 168.3, inj: "" },
  { id: "5870", name: "Daniel Jones", pos: "QB", team: "IND", bye: 13, adp: 169.4, inj: "" },
  { id: "BAL", name: "Baltimore Defense", pos: "DST", team: "BAL", bye: 13, adp: 169.7, inj: "" },
  { id: "650", name: "Nick Folk", pos: "K", team: "ATL", bye: 11, adp: 170.4, inj: "" },
  { id: "3678", name: "Wil Lutz", pos: "K", team: "DEN", bye: 10, adp: 170.7, inj: "" },
  { id: "10219", name: "Chris Rodriguez Jr.", pos: "RB", team: "JAX", bye: 7, adp: 170.8, inj: "" },
  { id: "NO", name: "New Orleans Defense", pos: "DST", team: "NO", bye: 8, adp: 178.6, inj: "" }
];
