/* ==========================================================
   Alpine Draft Room - player data
   GENERATED FILE. Edit scripts/build_players.py instead.

   Generated : 2026-08-16 11:40 UTC
   Players   : standard 210 · half 218 · ppr 261
   Seasons   : 2018-2025
   Matched   : 218 of the half set carry a Sleeper id
   Flagged   : 31 carry an injury designation
   Projected : 262 have 2026 projections

   ADP: Fantasy Football Calculator, one set per scoring format.
   Team count is not an axis: FFC returns the same sample for
   8, 10, 12 and 14 teams. See the note in build_players.py.
   Player, injury and stat data: Sleeper.
   ========================================================== */

const PLAYERS_META = { generated: "2026-08-16 11:40 UTC", count: 218, matched: 218, flagged: 31, projected: 262, unmatched: 0 };

/* One ordered list per scoring format. app.js picks the set that
   matches league.scoring when a draft starts, and works out every
   rank and tier from that set rather than from a fixed board. */
const ADP_SETS = {
  "standard": [
  { id: "9221", name: "Jahmyr Gibbs", pos: "RB", team: "DET", bye: 6, adp: 1.6, inj: "" },
  { id: "9509", name: "Bijan Robinson", pos: "RB", team: "ATL", bye: 11, adp: 2.2, inj: "" },
  { id: "9493", name: "Puka Nacua", pos: "WR", team: "LAR", bye: 11, adp: 3.6, inj: "Q" },
  { id: "6813", name: "Jonathan Taylor", pos: "RB", team: "IND", bye: 13, adp: 4.0, inj: "" },
  { id: "7564", name: "Ja'Marr Chase", pos: "WR", team: "CIN", bye: 6, adp: 4.8, inj: "" },
  { id: "9488", name: "Jaxon Smith-Njigba", pos: "WR", team: "SEA", bye: 11, adp: 6.2, inj: "" },
  { id: "4034", name: "Christian McCaffrey", pos: "RB", team: "SF", bye: 8, adp: 6.3, inj: "Q" },
  { id: "3198", name: "Derrick Henry", pos: "RB", team: "BAL", bye: 13, adp: 7.5, inj: "" },
  { id: "7547", name: "Amon-Ra St. Brown", pos: "WR", team: "DET", bye: 6, adp: 8.6, inj: "" },
  { id: "8138", name: "James Cook III", pos: "RB", team: "BUF", bye: 7, adp: 9.0, inj: "" },
  { id: "9226", name: "De'Von Achane", pos: "RB", team: "MIA", bye: 6, adp: 11.1, inj: "" },
  { id: "8112", name: "Drake London", pos: "WR", team: "ATL", bye: 11, adp: 11.9, inj: "" },
  { id: "6786", name: "CeeDee Lamb", pos: "WR", team: "DAL", bye: 14, adp: 13.7, inj: "" },
  { id: "4866", name: "Saquon Barkley", pos: "RB", team: "PHI", bye: 10, adp: 14.5, inj: "" },
  { id: "12527", name: "Ashton Jeanty", pos: "RB", team: "LV", bye: 13, adp: 16.5, inj: "" },
  { id: "8137", name: "George Pickens", pos: "WR", team: "DAL", bye: 14, adp: 16.8, inj: "" },
  { id: "6794", name: "Justin Jefferson", pos: "WR", team: "MIN", bye: 6, adp: 17.4, inj: "" },
  { id: "10229", name: "Rashee Rice", pos: "WR", team: "KC", bye: 5, adp: 18.5, inj: "" },
  { id: "9224", name: "Chase Brown", pos: "RB", team: "CIN", bye: 6, adp: 18.9, inj: "" },
  { id: "5859", name: "A.J. Brown", pos: "WR", team: "NE", bye: 11, adp: 19.4, inj: "" },
  { id: "5850", name: "Josh Jacobs", pos: "RB", team: "GB", bye: 11, adp: 20.2, inj: "Q" },
  { id: "4984", name: "Josh Allen", pos: "QB", team: "BUF", bye: 7, adp: 20.6, inj: "" },
  { id: "7569", name: "Nico Collins", pos: "WR", team: "HOU", bye: 8, adp: 21.5, inj: "" },
  { id: "12507", name: "Omarion Hampton", pos: "RB", team: "LAC", bye: 7, adp: 22.8, inj: "" },
  { id: "9997", name: "Zay Flowers", pos: "WR", team: "BAL", bye: 13, adp: 23.7, inj: "" },
  { id: "8150", name: "Kyren Williams", pos: "RB", team: "LAR", bye: 11, adp: 24.2, inj: "" },
  { id: "8151", name: "Kenneth Walker", pos: "RB", team: "KC", bye: 5, adp: 25.4, inj: "" },
  { id: "8144", name: "Chris Olave", pos: "WR", team: "NO", bye: 8, adp: 27.2, inj: "" },
  { id: "8155", name: "Breece Hall", pos: "RB", team: "NYJ", bye: 13, adp: 27.4, inj: "" },
  { id: "7588", name: "Javonte Williams", pos: "RB", team: "DAL", bye: 14, adp: 29.4, inj: "" },
  { id: "11632", name: "Malik Nabers", pos: "WR", team: "NYG", bye: 8, adp: 30.8, inj: "Q" },
  { id: "6801", name: "Tee Higgins", pos: "WR", team: "CIN", bye: 6, adp: 32.5, inj: "" },
  { id: "13287", name: "Jeremiyah Love", pos: "RB", team: "ARI", bye: 14, adp: 33.5, inj: "Q" },
  { id: "2133", name: "Davante Adams", pos: "WR", team: "LAR", bye: 11, adp: 34.0, inj: "" },
  { id: "12481", name: "Cam Skattebo", pos: "RB", team: "NYG", bye: 8, adp: 34.5, inj: "" },
  { id: "12514", name: "Emeka Egbuka", pos: "WR", team: "TB", bye: 10, adp: 35.7, inj: "Q" },
  { id: "12526", name: "Tetairoa McMillan", pos: "WR", team: "CAR", bye: 5, adp: 36.4, inj: "" },
  { id: "8148", name: "Jameson Williams", pos: "WR", team: "DET", bye: 6, adp: 37.6, inj: "" },
  { id: "7525", name: "DeVonta Smith", pos: "WR", team: "PHI", bye: 10, adp: 38.7, inj: "Q" },
  { id: "11620", name: "Rome Odunze", pos: "WR", team: "CHI", bye: 10, adp: 40.9, inj: "" },
  { id: "7543", name: "Travis Etienne Jr.", pos: "RB", team: "NO", bye: 8, adp: 41.4, inj: "" },
  { id: "8146", name: "Garrett Wilson", pos: "WR", team: "NYJ", bye: 13, adp: 41.6, inj: "" },
  { id: "6790", name: "D'Andre Swift", pos: "RB", team: "CHI", bye: 10, adp: 42.7, inj: "" },
  { id: "5927", name: "Terry McLaurin", pos: "WR", team: "WAS", bye: 7, adp: 44.4, inj: "" },
  { id: "8142", name: "Alec Pierce", pos: "WR", team: "IND", bye: 13, adp: 46.0, inj: "PUP" },
  { id: "11635", name: "Ladd McConkey", pos: "WR", team: "LAC", bye: 7, adp: 46.2, inj: "" },
  { id: "11584", name: "Bucky Irving", pos: "RB", team: "TB", bye: 10, adp: 46.6, inj: "" },
  { id: "11564", name: "Drake Maye", pos: "QB", team: "NE", bye: 11, adp: 48.1, inj: "" },
  { id: "12512", name: "Quinshon Judkins", pos: "RB", team: "CLE", bye: 11, adp: 48.6, inj: "" },
  { id: "4983", name: "DJ Moore", pos: "WR", team: "BUF", bye: 7, adp: 50.7, inj: "Q" },
  { id: "4881", name: "Lamar Jackson", pos: "QB", team: "BAL", bye: 13, adp: 51.2, inj: "" },
  { id: "12490", name: "Bhayshul Tuten", pos: "RB", team: "JAX", bye: 7, adp: 51.2, inj: "" },
  { id: "11604", name: "Brock Bowers", pos: "TE", team: "LV", bye: 13, adp: 52.2, inj: "" },
  { id: "7526", name: "Jaylen Waddle", pos: "WR", team: "DEN", bye: 10, adp: 52.6, inj: "Q" },
  { id: "8130", name: "Trey McBride", pos: "TE", team: "ARI", bye: 14, adp: 52.7, inj: "" },
  { id: "2216", name: "Mike Evans", pos: "WR", team: "SF", bye: 8, adp: 53.8, inj: "" },
  { id: "6770", name: "Joe Burrow", pos: "QB", team: "CIN", bye: 6, adp: 54.3, inj: "" },
  { id: "8167", name: "Christian Watson", pos: "WR", team: "GB", bye: 11, adp: 54.6, inj: "" },
  { id: "5045", name: "Courtland Sutton", pos: "WR", team: "DEN", bye: 10, adp: 56.4, inj: "" },
  { id: "12529", name: "TreVeyon Henderson", pos: "RB", team: "NE", bye: 11, adp: 56.9, inj: "" },
  { id: "5892", name: "David Montgomery", pos: "RB", team: "HOU", bye: 8, adp: 57.3, inj: "" },
  { id: "12519", name: "Luther Burden III", pos: "WR", team: "CHI", bye: 10, adp: 58.4, inj: "Q" },
  { id: "5846", name: "DK Metcalf", pos: "WR", team: "PIT", bye: 9, adp: 59.8, inj: "Q" },
  { id: "11628", name: "Marvin Harrison Jr.", pos: "WR", team: "ARI", bye: 14, adp: 63.2, inj: "" },
  { id: "3294", name: "Dak Prescott", pos: "QB", team: "DAL", bye: 14, adp: 63.4, inj: "" },
  { id: "5967", name: "Tony Pollard", pos: "RB", team: "TEN", bye: 9, adp: 64.9, inj: "" },
  { id: "9487", name: "Parker Washington", pos: "WR", team: "JAX", bye: 7, adp: 64.9, inj: "" },
  { id: "11631", name: "Brian Thomas Jr.", pos: "WR", team: "JAX", bye: 7, adp: 67.3, inj: "" },
  { id: "7611", name: "Rhamondre Stevenson", pos: "RB", team: "NE", bye: 11, adp: 67.7, inj: "" },
  { id: "13286", name: "Jadarian Price", pos: "RB", team: "SEA", bye: 11, adp: 69.0, inj: "Q" },
  { id: "11566", name: "Jayden Daniels", pos: "QB", team: "WAS", bye: 7, adp: 69.7, inj: "" },
  { id: "12517", name: "Colston Loveland", pos: "TE", team: "CHI", bye: 10, adp: 70.3, inj: "" },
  { id: "8228", name: "Jaylen Warren", pos: "RB", team: "PIT", bye: 9, adp: 71.9, inj: "" },
  { id: "13279", name: "Carnell Tate", pos: "WR", team: "TEN", bye: 9, adp: 72.3, inj: "" },
  { id: "6904", name: "Jalen Hurts", pos: "QB", team: "PHI", bye: 10, adp: 72.8, inj: "" },
  { id: "7021", name: "Rico Dowdle", pos: "RB", team: "PIT", bye: 9, adp: 72.9, inj: "" },
  { id: "9754", name: "Quentin Johnston", pos: "WR", team: "LAC", bye: 7, adp: 74.2, inj: "" },
  { id: "421", name: "Matthew Stafford", pos: "QB", team: "LAR", bye: 11, adp: 74.3, inj: "" },
  { id: "12518", name: "Tyler Warren", pos: "TE", team: "IND", bye: 13, adp: 77.5, inj: "" },
  { id: "7594", name: "Chuba Hubbard", pos: "RB", team: "CAR", bye: 5, adp: 78.2, inj: "Q" },
  { id: "6806", name: "J.K. Dobbins", pos: "RB", team: "DEN", bye: 10, adp: 78.7, inj: "Q" },
  { id: "10232", name: "Michael Wilson", pos: "WR", team: "ARI", bye: 14, adp: 80.7, inj: "" },
  { id: "9756", name: "Jordan Addison", pos: "WR", team: "MIN", bye: 6, adp: 80.9, inj: "" },
  { id: "8183", name: "Brock Purdy", pos: "QB", team: "SF", bye: 8, adp: 82.0, inj: "" },
  { id: "4037", name: "Chris Godwin Jr.", pos: "WR", team: "TB", bye: 10, adp: 83.9, inj: "" },
  { id: "10222", name: "Jayden Reed", pos: "WR", team: "GB", bye: 11, adp: 84.9, inj: "" },
  { id: "5947", name: "Jakobi Meyers", pos: "WR", team: "JAX", bye: 7, adp: 85.9, inj: "" },
  { id: "9484", name: "Tucker Kraft", pos: "TE", team: "GB", bye: 11, adp: 87.5, inj: "Q" },
  { id: "11624", name: "Xavier Worthy", pos: "WR", team: "KC", bye: 5, adp: 88.0, inj: "Q" },
  { id: "DEN", name: "Denver Defense", pos: "DST", team: "DEN", bye: 10, adp: 88.0, inj: "" },
  { id: "13281", name: "Jordyn Tyson", pos: "WR", team: "NO", bye: 8, adp: 88.6, inj: "Q" },
  { id: "7523", name: "Trevor Lawrence", pos: "QB", team: "JAX", bye: 7, adp: 90.9, inj: "" },
  { id: "SEA", name: "Seattle Defense", pos: "DST", team: "SEA", bye: 11, adp: 91.9, inj: "" },
  { id: "6819", name: "Michael Pittman Jr.", pos: "WR", team: "PIT", bye: 9, adp: 92.5, inj: "Q" },
  { id: "12489", name: "RJ Harvey", pos: "RB", team: "DEN", bye: 10, adp: 93.0, inj: "" },
  { id: "12533", name: "Jacory Croskey-Merritt", pos: "RB", team: "WAS", bye: 7, adp: 93.0, inj: "" },
  { id: "5872", name: "Deebo Samuel Sr.", pos: "WR", team: "SF", bye: 8, adp: 93.4, inj: "" },
  { id: "4046", name: "Patrick Mahomes", pos: "QB", team: "KC", bye: 5, adp: 97.6, inj: "Q" },
  { id: "11560", name: "Caleb Williams", pos: "QB", team: "CHI", bye: 10, adp: 98.1, inj: "" },
  { id: "13294", name: "Makai Lemon", pos: "WR", team: "PHI", bye: 10, adp: 98.9, inj: "Q" },
  { id: "9500", name: "Josh Downs", pos: "WR", team: "IND", bye: 13, adp: 99.6, inj: "Q" },
  { id: "8121", name: "Romeo Doubs", pos: "WR", team: "NE", bye: 11, adp: 99.7, inj: "" },
  { id: "2449", name: "Stefon Diggs", pos: "WR", team: "WAS", bye: 7, adp: 100.1, inj: "" },
  { id: "4199", name: "Aaron Jones Sr.", pos: "RB", team: "MIN", bye: 6, adp: 100.6, inj: "" },
  { id: "12506", name: "Harold Fannin Jr.", pos: "TE", team: "CLE", bye: 11, adp: 100.9, inj: "" },
  { id: "10859", name: "Sam LaPorta", pos: "TE", team: "DET", bye: 6, adp: 102.0, inj: "" },
  { id: "11638", name: "Ricky Pearsall", pos: "WR", team: "SF", bye: 8, adp: 102.5, inj: "IR" },
  { id: "12534", name: "Kyle Monangai", pos: "RB", team: "CHI", bye: 10, adp: 102.9, inj: "" },
  { id: "8126", name: "Wan'Dale Robinson", pos: "WR", team: "TEN", bye: 9, adp: 103.0, inj: "" },
  { id: "8676", name: "Rashid Shaheed", pos: "WR", team: "SEA", bye: 11, adp: 103.8, inj: "" },
  { id: "6797", name: "Justin Herbert", pos: "QB", team: "LAC", bye: 7, adp: 104.6, inj: "" },
  { id: "HOU", name: "Houston Defense", pos: "DST", team: "HOU", bye: 8, adp: 105.3, inj: "" },
  { id: "12501", name: "Matthew Golden", pos: "WR", team: "GB", bye: 11, adp: 105.3, inj: "" },
  { id: "3163", name: "Jared Goff", pos: "QB", team: "DET", bye: 6, adp: 107.5, inj: "" },
  { id: "11586", name: "Blake Corum", pos: "RB", team: "LAR", bye: 11, adp: 107.6, inj: "" },
  { id: "7553", name: "Kyle Pitts Sr.", pos: "TE", team: "ATL", bye: 11, adp: 108.7, inj: "" },
  { id: "8408", name: "Jordan Mason", pos: "RB", team: "MIN", bye: 6, adp: 109.2, inj: "" },
  { id: "5022", name: "Dallas Goedert", pos: "TE", team: "PHI", bye: 10, adp: 110.7, inj: "" },
  { id: "8134", name: "Khalil Shakir", pos: "WR", team: "BUF", bye: 7, adp: 111.3, inj: "" },
  { id: "12508", name: "Jaxson Dart", pos: "QB", team: "NYG", bye: 8, adp: 113.7, inj: "" },
  { id: "11583", name: "Jonathon Brooks", pos: "RB", team: "CAR", bye: 5, adp: 115.0, inj: "" },
  { id: "8136", name: "Rachaad White", pos: "RB", team: "WAS", bye: 7, adp: 117.7, inj: "" },
  { id: "4217", name: "George Kittle", pos: "TE", team: "SF", bye: 8, adp: 118.8, inj: "PUP" },
  { id: "12484", name: "Jayden Higgins", pos: "WR", team: "HOU", bye: 8, adp: 119.8, inj: "" },
  { id: "MIN", name: "Minnesota Defense", pos: "DST", team: "MIN", bye: 6, adp: 119.8, inj: "" },
  { id: "11646", name: "Jalen Coker", pos: "WR", team: "CAR", bye: 5, adp: 120.8, inj: "" },
  { id: "8154", name: "Brian Robinson", pos: "RB", team: "ATL", bye: 11, adp: 121.2, inj: "" },
  { id: "DET", name: "Detroit Defense", pos: "DST", team: "DET", bye: 6, adp: 121.3, inj: "" },
  { id: "11563", name: "Bo Nix", pos: "QB", team: "DEN", bye: 10, adp: 121.9, inj: "" },
  { id: "4981", name: "Calvin Ridley", pos: "WR", team: "TEN", bye: 9, adp: 122.1, inj: "" },
  { id: "7567", name: "Kenny Gainwell", pos: "RB", team: "TB", bye: 10, adp: 123.0, inj: "" },
  { id: "13298", name: "KC Concepcion", pos: "WR", team: "CLE", bye: 11, adp: 124.2, inj: "" },
  { id: "LAR", name: "LA Rams Defense", pos: "DST", team: "LAR", bye: 11, adp: 125.8, inj: "" },
  { id: "5012", name: "Mark Andrews", pos: "TE", team: "BAL", bye: 13, adp: 126.3, inj: "" },
  { id: "10213", name: "Tre Tucker", pos: "WR", team: "LV", bye: 13, adp: 127.5, inj: "" },
  { id: "NE", name: "New England Defense", pos: "DST", team: "NE", bye: 11, adp: 128.2, inj: "" },
  { id: "11533", name: "Brandon Aubrey", pos: "K", team: "DAL", bye: 14, adp: 129.3, inj: "" },
  { id: "PHI", name: "Philadelphia Defense", pos: "DST", team: "PHI", bye: 10, adp: 129.5, inj: "" },
  { id: "7571", name: "Rashod Bateman", pos: "WR", team: "BAL", bye: 13, adp: 129.8, inj: "" },
  { id: "1466", name: "Travis Kelce", pos: "TE", team: "KC", bye: 5, adp: 133.3, inj: "" },
  { id: "6783", name: "Jerry Jeudy", pos: "WR", team: "CLE", bye: 11, adp: 133.6, inj: "" },
  { id: "12015", name: "Harrison Mevis", pos: "K", team: "LAR", bye: 11, adp: 134.3, inj: "" },
  { id: "8131", name: "Isaiah Likely", pos: "TE", team: "NYG", bye: 8, adp: 134.6, inj: "" },
  { id: "8147", name: "John Metchie III", pos: "WR", team: "CAR", bye: 5, adp: 134.7, inj: "" },
  { id: "2747", name: "Jason Myers", pos: "K", team: "SEA", bye: 11, adp: 135.6, inj: "" },
  { id: "12860", name: "Theo Wease Jr.", pos: "WR", team: "MIA", bye: 6, adp: 135.8, inj: "" },
  { id: "4892", name: "Baker Mayfield", pos: "QB", team: "TB", bye: 10, adp: 136.5, inj: "" },
  { id: "9753", name: "Zach Charbonnet", pos: "RB", team: "SEA", bye: 11, adp: 137.5, inj: "PUP" },
  { id: "10219", name: "Chris Rodriguez Jr.", pos: "RB", team: "JAX", bye: 7, adp: 138.9, inj: "" },
  { id: "11618", name: "Jalen McMillan", pos: "WR", team: "TB", bye: 10, adp: 139.5, inj: "Q" },
  { id: "8180", name: "Jalen Nailor", pos: "WR", team: "LV", bye: 13, adp: 140.9, inj: "" },
  { id: "3451", name: "Ka'imi Fairbairn", pos: "K", team: "HOU", bye: 8, adp: 141.0, inj: "" },
  { id: "12545", name: "Tyler Shough", pos: "QB", team: "NO", bye: 8, adp: 141.4, inj: "" },
  { id: "PIT", name: "Pittsburgh Defense", pos: "DST", team: "PIT", bye: 9, adp: 142.0, inj: "" },
  { id: "10236", name: "Dalton Kincaid", pos: "TE", team: "BUF", bye: 7, adp: 142.3, inj: "" },
  { id: "7049", name: "Jauan Jennings", pos: "WR", team: "MIN", bye: 6, adp: 142.7, inj: "" },
  { id: "LAC", name: "LA Chargers Defense", pos: "DST", team: "LAC", bye: 7, adp: 143.3, inj: "" },
  { id: "KC", name: "Kansas City Defense", pos: "DST", team: "KC", bye: 5, adp: 143.5, inj: "" },
  { id: "12474", name: "Woody Marks", pos: "RB", team: "HOU", bye: 8, adp: 144.2, inj: "" },
  { id: "13346", name: "Denzel Boston", pos: "WR", team: "CLE", bye: 11, adp: 145.6, inj: "" },
  { id: "11539", name: "Jake Bates", pos: "K", team: "DET", bye: 6, adp: 147.2, inj: "" },
  { id: "8259", name: "Cameron Dicker", pos: "K", team: "LAC", bye: 7, adp: 147.8, inj: "" },
  { id: "11655", name: "Tyrone Tracy Jr.", pos: "RB", team: "NYG", bye: 8, adp: 147.8, inj: "" },
  { id: "13417", name: "De'Zhaun Stribling", pos: "WR", team: "SF", bye: 8, adp: 148.1, inj: "" },
  { id: "9511", name: "Keaton Mitchell", pos: "RB", team: "LAC", bye: 7, adp: 148.2, inj: "" },
  { id: "4035", name: "Alvin Kamara", pos: "RB", team: "NO", bye: 8, adp: 150.1, inj: "" },
  { id: "9502", name: "Tank Dell", pos: "WR", team: "HOU", bye: 8, adp: 150.2, inj: "Q" },
  { id: "9225", name: "Tank Bigsby", pos: "RB", team: "PHI", bye: 10, adp: 150.4, inj: "" },
  { id: "5870", name: "Daniel Jones", pos: "QB", team: "IND", bye: 13, adp: 151.2, inj: "" },
  { id: "11786", name: "Cam Little", pos: "K", team: "JAX", bye: 7, adp: 151.2, inj: "" },
  { id: "8110", name: "Jake Ferguson", pos: "TE", team: "DAL", bye: 14, adp: 151.6, inj: "" },
  { id: "JAX", name: "Jacksonville Defense", pos: "DST", team: "JAX", bye: 7, adp: 151.9, inj: "" },
  { id: "5849", name: "Kyler Murray", pos: "QB", team: "MIN", bye: 6, adp: 152.1, inj: "" },
  { id: "6650", name: "Chase McLaughlin", pos: "K", team: "TB", bye: 10, adp: 152.6, inj: "" },
  { id: "3214", name: "Hunter Henry", pos: "TE", team: "NE", bye: 11, adp: 153.1, inj: "" },
  { id: "13301", name: "Antonio Williams", pos: "WR", team: "WAS", bye: 7, adp: 153.2, inj: "" },
  { id: "11783", name: "Ryan Flournoy", pos: "WR", team: "DAL", bye: 14, adp: 153.4, inj: "" },
  { id: "4039", name: "Cooper Kupp", pos: "WR", team: "SEA", bye: 11, adp: 153.4, inj: "" },
  { id: "4943", name: "Sam Darnold", pos: "QB", team: "SEA", bye: 11, adp: 153.9, inj: "" },
  { id: "8205", name: "Isiah Pacheco", pos: "RB", team: "DET", bye: 6, adp: 154.1, inj: "Q" },
  { id: "8161", name: "Malik Willis", pos: "QB", team: "MIA", bye: 6, adp: 154.1, inj: "" },
  { id: "8132", name: "Tyler Allgeier", pos: "RB", team: "ARI", bye: 14, adp: 155.3, inj: "" },
  { id: "11610", name: "Malik Washington", pos: "WR", team: "MIA", bye: 6, adp: 155.6, inj: "" },
  { id: "650", name: "Nick Folk", pos: "K", team: "ATL", bye: 11, adp: 156.6, inj: "" },
  { id: "9758", name: "C.J. Stroud", pos: "QB", team: "HOU", bye: 8, adp: 157.1, inj: "" },
  { id: "13293", name: "Ja'Kobi Lane", pos: "WR", team: "BAL", bye: 13, adp: 157.8, inj: "" },
  { id: "6804", name: "Jordan Love", pos: "QB", team: "GB", bye: 11, adp: 158.5, inj: "" },
  { id: "9480", name: "Brenton Strange", pos: "TE", team: "JAX", bye: 7, adp: 158.7, inj: "" },
  { id: "12711", name: "Tyler Loop", pos: "K", team: "BAL", bye: 13, adp: 159.3, inj: "" },
  { id: "9504", name: "Kayshon Boutte", pos: "WR", team: "NE", bye: 11, adp: 159.5, inj: "" },
  { id: "11625", name: "Adonai Mitchell", pos: "WR", team: "NYJ", bye: 13, adp: 159.6, inj: "" },
  { id: "CLE", name: "Cleveland Defense", pos: "DST", team: "CLE", bye: 11, adp: 160.1, inj: "" },
  { id: "13330", name: "Kenyon Sadiq", pos: "TE", team: "NYJ", bye: 13, adp: 160.2, inj: "Q" },
  { id: "TEN", name: "Tennessee Defense", pos: "DST", team: "TEN", bye: 9, adp: 161.3, inj: "" },
  { id: "12457", name: "Jaydon Blue", pos: "RB", team: "DAL", bye: 14, adp: 161.4, inj: "" },
  { id: "9508", name: "Tyjae Spears", pos: "RB", team: "TEN", bye: 9, adp: 161.7, inj: "" },
  { id: "12530", name: "Travis Hunter", pos: "WR", team: "JAX", bye: 7, adp: 161.8, inj: "" },
  { id: "BAL", name: "Baltimore Defense", pos: "DST", team: "BAL", bye: 13, adp: 162.3, inj: "" },
  { id: "BUF", name: "Buffalo Defense", pos: "DST", team: "BUF", bye: 7, adp: 162.3, inj: "" },
  { id: "13276", name: "Omar Cooper Jr.", pos: "WR", team: "NYJ", bye: 13, adp: 162.8, inj: "" },
  { id: "13274", name: "Germie Bernard", pos: "WR", team: "PIT", bye: 9, adp: 163.0, inj: "" },
  { id: "13345", name: "Jonah Coleman", pos: "RB", team: "DEN", bye: 10, adp: 163.5, inj: "" },
  { id: "11792", name: "Will Reichard", pos: "K", team: "MIN", bye: 6, adp: 164.9, inj: "" },
  { id: "2020", name: "Cairo Santos", pos: "K", team: "CHI", bye: 10, adp: 165.0, inj: "" },
  { id: "5189", name: "Eddy Piñeiro", pos: "K", team: "SF", bye: 8, adp: 165.2, inj: "" },
  { id: "4227", name: "Harrison Butker", pos: "K", team: "KC", bye: 5, adp: 165.7, inj: "" },
  { id: "3678", name: "Wil Lutz", pos: "K", team: "DEN", bye: 10, adp: 167.6, inj: "" },
  { id: "1945", name: "Chris Boswell", pos: "K", team: "PIT", bye: 9, adp: 169.9, inj: "" },
  { id: "NYG", name: "NY Giants Defense", pos: "DST", team: "NYG", bye: 8, adp: 172.4, inj: "" },
  { id: "7839", name: "Evan McPherson", pos: "K", team: "CIN", bye: 6, adp: 172.6, inj: "" }
  ],

  "half": [
  { id: "9221", name: "Jahmyr Gibbs", pos: "RB", team: "DET", bye: 6, adp: 1.5, inj: "" },
  { id: "9509", name: "Bijan Robinson", pos: "RB", team: "ATL", bye: 11, adp: 2.1, inj: "" },
  { id: "9493", name: "Puka Nacua", pos: "WR", team: "LAR", bye: 11, adp: 2.9, inj: "Q" },
  { id: "7564", name: "Ja'Marr Chase", pos: "WR", team: "CIN", bye: 6, adp: 4.1, inj: "" },
  { id: "9488", name: "Jaxon Smith-Njigba", pos: "WR", team: "SEA", bye: 11, adp: 5.4, inj: "" },
  { id: "6813", name: "Jonathan Taylor", pos: "RB", team: "IND", bye: 13, adp: 5.9, inj: "" },
  { id: "4034", name: "Christian McCaffrey", pos: "RB", team: "SF", bye: 8, adp: 6.7, inj: "Q" },
  { id: "7547", name: "Amon-Ra St. Brown", pos: "WR", team: "DET", bye: 6, adp: 7.6, inj: "" },
  { id: "8138", name: "James Cook III", pos: "RB", team: "BUF", bye: 7, adp: 9.7, inj: "" },
  { id: "3198", name: "Derrick Henry", pos: "RB", team: "BAL", bye: 13, adp: 10.5, inj: "" },
  { id: "8112", name: "Drake London", pos: "WR", team: "ATL", bye: 11, adp: 11.3, inj: "" },
  { id: "9226", name: "De'Von Achane", pos: "RB", team: "MIA", bye: 6, adp: 11.4, inj: "" },
  { id: "6786", name: "CeeDee Lamb", pos: "WR", team: "DAL", bye: 14, adp: 12.6, inj: "" },
  { id: "6794", name: "Justin Jefferson", pos: "WR", team: "MIN", bye: 6, adp: 14.4, inj: "" },
  { id: "9224", name: "Chase Brown", pos: "RB", team: "CIN", bye: 6, adp: 14.9, inj: "" },
  { id: "10229", name: "Rashee Rice", pos: "WR", team: "KC", bye: 5, adp: 15.6, inj: "" },
  { id: "12527", name: "Ashton Jeanty", pos: "RB", team: "LV", bye: 13, adp: 15.6, inj: "" },
  { id: "4866", name: "Saquon Barkley", pos: "RB", team: "PHI", bye: 10, adp: 18.1, inj: "" },
  { id: "5859", name: "A.J. Brown", pos: "WR", team: "NE", bye: 11, adp: 18.8, inj: "" },
  { id: "8137", name: "George Pickens", pos: "WR", team: "DAL", bye: 14, adp: 19.3, inj: "" },
  { id: "7569", name: "Nico Collins", pos: "WR", team: "HOU", bye: 8, adp: 21.9, inj: "" },
  { id: "12507", name: "Omarion Hampton", pos: "RB", team: "LAC", bye: 7, adp: 22.1, inj: "" },
  { id: "8151", name: "Kenneth Walker", pos: "RB", team: "KC", bye: 5, adp: 23.5, inj: "" },
  { id: "8144", name: "Chris Olave", pos: "WR", team: "NO", bye: 8, adp: 24.1, inj: "" },
  { id: "9997", name: "Zay Flowers", pos: "WR", team: "BAL", bye: 13, adp: 24.5, inj: "" },
  { id: "5850", name: "Josh Jacobs", pos: "RB", team: "GB", bye: 11, adp: 25.8, inj: "Q" },
  { id: "11632", name: "Malik Nabers", pos: "WR", team: "NYG", bye: 8, adp: 27.9, inj: "Q" },
  { id: "8155", name: "Breece Hall", pos: "RB", team: "NYJ", bye: 13, adp: 28.5, inj: "" },
  { id: "8150", name: "Kyren Williams", pos: "RB", team: "LAR", bye: 11, adp: 28.5, inj: "" },
  { id: "4984", name: "Josh Allen", pos: "QB", team: "BUF", bye: 7, adp: 29.5, inj: "" },
  { id: "8146", name: "Garrett Wilson", pos: "WR", team: "NYJ", bye: 13, adp: 30.8, inj: "" },
  { id: "7525", name: "DeVonta Smith", pos: "WR", team: "PHI", bye: 10, adp: 31.2, inj: "Q" },
  { id: "13287", name: "Jeremiyah Love", pos: "RB", team: "ARI", bye: 14, adp: 32.1, inj: "Q" },
  { id: "12481", name: "Cam Skattebo", pos: "RB", team: "NYG", bye: 8, adp: 34.9, inj: "" },
  { id: "12526", name: "Tetairoa McMillan", pos: "WR", team: "CAR", bye: 5, adp: 35.0, inj: "" },
  { id: "7588", name: "Javonte Williams", pos: "RB", team: "DAL", bye: 14, adp: 35.1, inj: "" },
  { id: "6801", name: "Tee Higgins", pos: "WR", team: "CIN", bye: 6, adp: 35.3, inj: "" },
  { id: "12514", name: "Emeka Egbuka", pos: "WR", team: "TB", bye: 10, adp: 36.7, inj: "Q" },
  { id: "2133", name: "Davante Adams", pos: "WR", team: "LAR", bye: 11, adp: 37.4, inj: "" },
  { id: "8148", name: "Jameson Williams", pos: "WR", team: "DET", bye: 6, adp: 39.4, inj: "" },
  { id: "8130", name: "Trey McBride", pos: "TE", team: "ARI", bye: 14, adp: 40.5, inj: "" },
  { id: "11635", name: "Ladd McConkey", pos: "WR", team: "LAC", bye: 7, adp: 41.8, inj: "" },
  { id: "11604", name: "Brock Bowers", pos: "TE", team: "LV", bye: 13, adp: 42.5, inj: "" },
  { id: "7543", name: "Travis Etienne Jr.", pos: "RB", team: "NO", bye: 8, adp: 42.7, inj: "" },
  { id: "6790", name: "D'Andre Swift", pos: "RB", team: "CHI", bye: 10, adp: 43.3, inj: "" },
  { id: "5927", name: "Terry McLaurin", pos: "WR", team: "WAS", bye: 7, adp: 43.9, inj: "" },
  { id: "11620", name: "Rome Odunze", pos: "WR", team: "CHI", bye: 10, adp: 45.5, inj: "" },
  { id: "7526", name: "Jaylen Waddle", pos: "WR", team: "DEN", bye: 10, adp: 46.9, inj: "Q" },
  { id: "11584", name: "Bucky Irving", pos: "RB", team: "TB", bye: 10, adp: 48.1, inj: "" },
  { id: "4983", name: "DJ Moore", pos: "WR", team: "BUF", bye: 7, adp: 50.0, inj: "Q" },
  { id: "11564", name: "Drake Maye", pos: "QB", team: "NE", bye: 11, adp: 50.3, inj: "" },
  { id: "12512", name: "Quinshon Judkins", pos: "RB", team: "CLE", bye: 11, adp: 52.0, inj: "" },
  { id: "12490", name: "Bhayshul Tuten", pos: "RB", team: "JAX", bye: 7, adp: 53.3, inj: "" },
  { id: "2216", name: "Mike Evans", pos: "WR", team: "SF", bye: 8, adp: 53.4, inj: "" },
  { id: "8142", name: "Alec Pierce", pos: "WR", team: "IND", bye: 13, adp: 55.0, inj: "PUP" },
  { id: "4881", name: "Lamar Jackson", pos: "QB", team: "BAL", bye: 13, adp: 55.1, inj: "" },
  { id: "6770", name: "Joe Burrow", pos: "QB", team: "CIN", bye: 6, adp: 55.1, inj: "" },
  { id: "5892", name: "David Montgomery", pos: "RB", team: "HOU", bye: 8, adp: 57.6, inj: "" },
  { id: "12519", name: "Luther Burden III", pos: "WR", team: "CHI", bye: 10, adp: 58.3, inj: "Q" },
  { id: "8167", name: "Christian Watson", pos: "WR", team: "GB", bye: 11, adp: 58.5, inj: "" },
  { id: "12529", name: "TreVeyon Henderson", pos: "RB", team: "NE", bye: 11, adp: 58.5, inj: "" },
  { id: "12517", name: "Colston Loveland", pos: "TE", team: "CHI", bye: 10, adp: 60.2, inj: "" },
  { id: "5045", name: "Courtland Sutton", pos: "WR", team: "DEN", bye: 10, adp: 61.0, inj: "" },
  { id: "11628", name: "Marvin Harrison Jr.", pos: "WR", team: "ARI", bye: 14, adp: 62.6, inj: "" },
  { id: "5846", name: "DK Metcalf", pos: "WR", team: "PIT", bye: 9, adp: 63.0, inj: "Q" },
  { id: "9487", name: "Parker Washington", pos: "WR", team: "JAX", bye: 7, adp: 65.6, inj: "" },
  { id: "3294", name: "Dak Prescott", pos: "QB", team: "DAL", bye: 14, adp: 66.1, inj: "" },
  { id: "5967", name: "Tony Pollard", pos: "RB", team: "TEN", bye: 9, adp: 66.4, inj: "" },
  { id: "8228", name: "Jaylen Warren", pos: "RB", team: "PIT", bye: 9, adp: 68.0, inj: "" },
  { id: "12518", name: "Tyler Warren", pos: "TE", team: "IND", bye: 13, adp: 69.9, inj: "" },
  { id: "11631", name: "Brian Thomas Jr.", pos: "WR", team: "JAX", bye: 7, adp: 70.3, inj: "" },
  { id: "7611", name: "Rhamondre Stevenson", pos: "RB", team: "NE", bye: 11, adp: 70.5, inj: "" },
  { id: "11566", name: "Jayden Daniels", pos: "QB", team: "WAS", bye: 7, adp: 72.2, inj: "" },
  { id: "7594", name: "Chuba Hubbard", pos: "RB", team: "CAR", bye: 5, adp: 73.0, inj: "Q" },
  { id: "13279", name: "Carnell Tate", pos: "WR", team: "TEN", bye: 9, adp: 74.0, inj: "" },
  { id: "421", name: "Matthew Stafford", pos: "QB", team: "LAR", bye: 11, adp: 75.6, inj: "" },
  { id: "13286", name: "Jadarian Price", pos: "RB", team: "SEA", bye: 11, adp: 76.6, inj: "Q" },
  { id: "6904", name: "Jalen Hurts", pos: "QB", team: "PHI", bye: 10, adp: 76.8, inj: "" },
  { id: "10232", name: "Michael Wilson", pos: "WR", team: "ARI", bye: 14, adp: 76.8, inj: "" },
  { id: "7021", name: "Rico Dowdle", pos: "RB", team: "PIT", bye: 9, adp: 77.3, inj: "" },
  { id: "4037", name: "Chris Godwin Jr.", pos: "WR", team: "TB", bye: 10, adp: 81.0, inj: "" },
  { id: "6819", name: "Michael Pittman Jr.", pos: "WR", team: "PIT", bye: 9, adp: 81.1, inj: "Q" },
  { id: "12506", name: "Harold Fannin Jr.", pos: "TE", team: "CLE", bye: 11, adp: 81.1, inj: "" },
  { id: "7553", name: "Kyle Pitts Sr.", pos: "TE", team: "ATL", bye: 11, adp: 82.1, inj: "" },
  { id: "9754", name: "Quentin Johnston", pos: "WR", team: "LAC", bye: 7, adp: 84.2, inj: "" },
  { id: "8183", name: "Brock Purdy", pos: "QB", team: "SF", bye: 8, adp: 85.7, inj: "" },
  { id: "12489", name: "RJ Harvey", pos: "RB", team: "DEN", bye: 10, adp: 87.0, inj: "" },
  { id: "9500", name: "Josh Downs", pos: "WR", team: "IND", bye: 13, adp: 87.1, inj: "Q" },
  { id: "5947", name: "Jakobi Meyers", pos: "WR", team: "JAX", bye: 7, adp: 87.4, inj: "" },
  { id: "DEN", name: "Denver Defense", pos: "DST", team: "DEN", bye: 10, adp: 87.6, inj: "" },
  { id: "10859", name: "Sam LaPorta", pos: "TE", team: "DET", bye: 6, adp: 89.0, inj: "" },
  { id: "10222", name: "Jayden Reed", pos: "WR", team: "GB", bye: 11, adp: 89.4, inj: "" },
  { id: "6806", name: "J.K. Dobbins", pos: "RB", team: "DEN", bye: 10, adp: 89.8, inj: "Q" },
  { id: "9756", name: "Jordan Addison", pos: "WR", team: "MIN", bye: 6, adp: 90.6, inj: "" },
  { id: "8126", name: "Wan'Dale Robinson", pos: "WR", team: "TEN", bye: 9, adp: 90.8, inj: "" },
  { id: "SEA", name: "Seattle Defense", pos: "DST", team: "SEA", bye: 11, adp: 91.5, inj: "" },
  { id: "13281", name: "Jordyn Tyson", pos: "WR", team: "NO", bye: 8, adp: 91.8, inj: "Q" },
  { id: "11560", name: "Caleb Williams", pos: "QB", team: "CHI", bye: 10, adp: 92.2, inj: "" },
  { id: "7523", name: "Trevor Lawrence", pos: "QB", team: "JAX", bye: 7, adp: 93.6, inj: "" },
  { id: "9484", name: "Tucker Kraft", pos: "TE", team: "GB", bye: 11, adp: 94.2, inj: "Q" },
  { id: "2449", name: "Stefon Diggs", pos: "WR", team: "WAS", bye: 7, adp: 98.1, inj: "" },
  { id: "4199", name: "Aaron Jones Sr.", pos: "RB", team: "MIN", bye: 6, adp: 98.5, inj: "" },
  { id: "4046", name: "Patrick Mahomes", pos: "QB", team: "KC", bye: 5, adp: 99.3, inj: "Q" },
  { id: "11624", name: "Xavier Worthy", pos: "WR", team: "KC", bye: 5, adp: 100.9, inj: "Q" },
  { id: "7567", name: "Kenny Gainwell", pos: "RB", team: "TB", bye: 10, adp: 101.1, inj: "" },
  { id: "HOU", name: "Houston Defense", pos: "DST", team: "HOU", bye: 8, adp: 101.5, inj: "" },
  { id: "5872", name: "Deebo Samuel Sr.", pos: "WR", team: "SF", bye: 8, adp: 103.1, inj: "" },
  { id: "8134", name: "Khalil Shakir", pos: "WR", team: "BUF", bye: 7, adp: 103.7, inj: "" },
  { id: "13294", name: "Makai Lemon", pos: "WR", team: "PHI", bye: 10, adp: 105.1, inj: "Q" },
  { id: "3163", name: "Jared Goff", pos: "QB", team: "DET", bye: 6, adp: 105.6, inj: "" },
  { id: "6797", name: "Justin Herbert", pos: "QB", team: "LAC", bye: 7, adp: 106.2, inj: "" },
  { id: "8121", name: "Romeo Doubs", pos: "WR", team: "NE", bye: 11, adp: 108.2, inj: "" },
  { id: "12533", name: "Jacory Croskey-Merritt", pos: "RB", team: "WAS", bye: 7, adp: 109.5, inj: "" },
  { id: "8136", name: "Rachaad White", pos: "RB", team: "WAS", bye: 7, adp: 110.5, inj: "" },
  { id: "11583", name: "Jonathon Brooks", pos: "RB", team: "CAR", bye: 5, adp: 110.6, inj: "" },
  { id: "12534", name: "Kyle Monangai", pos: "RB", team: "CHI", bye: 10, adp: 110.7, inj: "" },
  { id: "12501", name: "Matthew Golden", pos: "WR", team: "GB", bye: 11, adp: 111.0, inj: "" },
  { id: "11638", name: "Ricky Pearsall", pos: "WR", team: "SF", bye: 8, adp: 111.2, inj: "IR" },
  { id: "5022", name: "Dallas Goedert", pos: "TE", team: "PHI", bye: 10, adp: 112.8, inj: "" },
  { id: "8408", name: "Jordan Mason", pos: "RB", team: "MIN", bye: 6, adp: 113.8, inj: "" },
  { id: "11646", name: "Jalen Coker", pos: "WR", team: "CAR", bye: 5, adp: 114.5, inj: "" },
  { id: "12508", name: "Jaxson Dart", pos: "QB", team: "NYG", bye: 8, adp: 115.0, inj: "" },
  { id: "4217", name: "George Kittle", pos: "TE", team: "SF", bye: 8, adp: 115.5, inj: "PUP" },
  { id: "LAR", name: "LA Rams Defense", pos: "DST", team: "LAR", bye: 11, adp: 116.0, inj: "" },
  { id: "11563", name: "Bo Nix", pos: "QB", team: "DEN", bye: 10, adp: 117.2, inj: "" },
  { id: "MIN", name: "Minnesota Defense", pos: "DST", team: "MIN", bye: 6, adp: 117.7, inj: "" },
  { id: "12484", name: "Jayden Higgins", pos: "WR", team: "HOU", bye: 8, adp: 120.9, inj: "" },
  { id: "8676", name: "Rashid Shaheed", pos: "WR", team: "SEA", bye: 11, adp: 121.3, inj: "" },
  { id: "11586", name: "Blake Corum", pos: "RB", team: "LAR", bye: 11, adp: 121.5, inj: "" },
  { id: "1466", name: "Travis Kelce", pos: "TE", team: "KC", bye: 5, adp: 122.3, inj: "" },
  { id: "13298", name: "KC Concepcion", pos: "WR", team: "CLE", bye: 11, adp: 124.6, inj: "" },
  { id: "NE", name: "New England Defense", pos: "DST", team: "NE", bye: 11, adp: 125.3, inj: "" },
  { id: "PHI", name: "Philadelphia Defense", pos: "DST", team: "PHI", bye: 10, adp: 126.0, inj: "" },
  { id: "11533", name: "Brandon Aubrey", pos: "K", team: "DAL", bye: 14, adp: 128.8, inj: "" },
  { id: "7571", name: "Rashod Bateman", pos: "WR", team: "BAL", bye: 13, adp: 130.1, inj: "" },
  { id: "DET", name: "Detroit Defense", pos: "DST", team: "DET", bye: 6, adp: 131.1, inj: "" },
  { id: "9753", name: "Zach Charbonnet", pos: "RB", team: "SEA", bye: 11, adp: 133.2, inj: "PUP" },
  { id: "4892", name: "Baker Mayfield", pos: "QB", team: "TB", bye: 10, adp: 133.4, inj: "" },
  { id: "6783", name: "Jerry Jeudy", pos: "WR", team: "CLE", bye: 11, adp: 133.6, inj: "" },
  { id: "5012", name: "Mark Andrews", pos: "TE", team: "BAL", bye: 13, adp: 133.6, inj: "" },
  { id: "11618", name: "Jalen McMillan", pos: "WR", team: "TB", bye: 10, adp: 134.0, inj: "Q" },
  { id: "12545", name: "Tyler Shough", pos: "QB", team: "NO", bye: 8, adp: 135.0, inj: "" },
  { id: "10213", name: "Tre Tucker", pos: "WR", team: "LV", bye: 13, adp: 135.8, inj: "" },
  { id: "3451", name: "Ka'imi Fairbairn", pos: "K", team: "HOU", bye: 8, adp: 135.9, inj: "" },
  { id: "4981", name: "Calvin Ridley", pos: "WR", team: "TEN", bye: 9, adp: 136.7, inj: "" },
  { id: "8131", name: "Isaiah Likely", pos: "TE", team: "NYG", bye: 8, adp: 137.4, inj: "" },
  { id: "12860", name: "Theo Wease Jr.", pos: "WR", team: "MIA", bye: 6, adp: 138.7, inj: "" },
  { id: "7049", name: "Jauan Jennings", pos: "WR", team: "MIN", bye: 6, adp: 140.4, inj: "" },
  { id: "2747", name: "Jason Myers", pos: "K", team: "SEA", bye: 11, adp: 140.6, inj: "" },
  { id: "8180", name: "Jalen Nailor", pos: "WR", team: "LV", bye: 13, adp: 140.7, inj: "" },
  { id: "12015", name: "Harrison Mevis", pos: "K", team: "LAR", bye: 11, adp: 141.5, inj: "" },
  { id: "5849", name: "Kyler Murray", pos: "QB", team: "MIN", bye: 6, adp: 141.8, inj: "" },
  { id: "8259", name: "Cameron Dicker", pos: "K", team: "LAC", bye: 7, adp: 142.2, inj: "" },
  { id: "13346", name: "Denzel Boston", pos: "WR", team: "CLE", bye: 11, adp: 142.4, inj: "" },
  { id: "LAC", name: "LA Chargers Defense", pos: "DST", team: "LAC", bye: 7, adp: 143.1, inj: "" },
  { id: "10236", name: "Dalton Kincaid", pos: "TE", team: "BUF", bye: 7, adp: 143.9, inj: "" },
  { id: "13417", name: "De'Zhaun Stribling", pos: "WR", team: "SF", bye: 8, adp: 144.4, inj: "" },
  { id: "3214", name: "Hunter Henry", pos: "TE", team: "NE", bye: 11, adp: 144.5, inj: "" },
  { id: "PIT", name: "Pittsburgh Defense", pos: "DST", team: "PIT", bye: 9, adp: 145.0, inj: "" },
  { id: "4943", name: "Sam Darnold", pos: "QB", team: "SEA", bye: 11, adp: 146.0, inj: "" },
  { id: "9508", name: "Tyjae Spears", pos: "RB", team: "TEN", bye: 9, adp: 146.2, inj: "" },
  { id: "12474", name: "Woody Marks", pos: "RB", team: "HOU", bye: 8, adp: 146.2, inj: "" },
  { id: "8110", name: "Jake Ferguson", pos: "TE", team: "DAL", bye: 14, adp: 147.2, inj: "" },
  { id: "8205", name: "Isiah Pacheco", pos: "RB", team: "DET", bye: 6, adp: 147.6, inj: "Q" },
  { id: "4035", name: "Alvin Kamara", pos: "RB", team: "NO", bye: 8, adp: 148.0, inj: "" },
  { id: "6804", name: "Jordan Love", pos: "QB", team: "GB", bye: 11, adp: 148.7, inj: "" },
  { id: "11610", name: "Malik Washington", pos: "WR", team: "MIA", bye: 6, adp: 149.4, inj: "" },
  { id: "6650", name: "Chase McLaughlin", pos: "K", team: "TB", bye: 10, adp: 149.5, inj: "" },
  { id: "9511", name: "Keaton Mitchell", pos: "RB", team: "LAC", bye: 7, adp: 150.4, inj: "" },
  { id: "4039", name: "Cooper Kupp", pos: "WR", team: "SEA", bye: 11, adp: 150.4, inj: "" },
  { id: "12711", name: "Tyler Loop", pos: "K", team: "BAL", bye: 13, adp: 151.2, inj: "" },
  { id: "JAX", name: "Jacksonville Defense", pos: "DST", team: "JAX", bye: 7, adp: 151.5, inj: "" },
  { id: "11655", name: "Tyrone Tracy Jr.", pos: "RB", team: "NYG", bye: 8, adp: 151.6, inj: "" },
  { id: "13345", name: "Jonah Coleman", pos: "RB", team: "DEN", bye: 10, adp: 152.1, inj: "" },
  { id: "11792", name: "Will Reichard", pos: "K", team: "MIN", bye: 6, adp: 154.3, inj: "" },
  { id: "11539", name: "Jake Bates", pos: "K", team: "DET", bye: 6, adp: 154.5, inj: "" },
  { id: "10219", name: "Chris Rodriguez Jr.", pos: "RB", team: "JAX", bye: 7, adp: 154.6, inj: "" },
  { id: "9228", name: "Bryce Young", pos: "QB", team: "CAR", bye: 5, adp: 156.0, inj: "" },
  { id: "11786", name: "Cam Little", pos: "K", team: "JAX", bye: 7, adp: 157.6, inj: "" },
  { id: "BUF", name: "Buffalo Defense", pos: "DST", team: "BUF", bye: 7, adp: 158.3, inj: "" },
  { id: "12530", name: "Travis Hunter", pos: "WR", team: "JAX", bye: 7, adp: 158.8, inj: "" },
  { id: "9502", name: "Tank Dell", pos: "WR", team: "HOU", bye: 8, adp: 159.0, inj: "Q" },
  { id: "9480", name: "Brenton Strange", pos: "TE", team: "JAX", bye: 7, adp: 159.3, inj: "" },
  { id: "8132", name: "Tyler Allgeier", pos: "RB", team: "ARI", bye: 14, adp: 159.4, inj: "" },
  { id: "11576", name: "Braelon Allen", pos: "RB", team: "NYJ", bye: 13, adp: 159.4, inj: "" },
  { id: "13414", name: "Kaelon Black", pos: "RB", team: "SF", bye: 8, adp: 160.7, inj: "Q" },
  { id: "BAL", name: "Baltimore Defense", pos: "DST", team: "BAL", bye: 13, adp: 160.9, inj: "" },
  { id: "11625", name: "Adonai Mitchell", pos: "WR", team: "NYJ", bye: 13, adp: 161.2, inj: "" },
  { id: "13293", name: "Ja'Kobi Lane", pos: "WR", team: "BAL", bye: 13, adp: 162.6, inj: "" },
  { id: "11783", name: "Ryan Flournoy", pos: "WR", team: "DAL", bye: 14, adp: 162.8, inj: "" },
  { id: "13276", name: "Omar Cooper Jr.", pos: "WR", team: "NYJ", bye: 13, adp: 163.3, inj: "" },
  { id: "8161", name: "Malik Willis", pos: "QB", team: "MIA", bye: 6, adp: 164.1, inj: "" },
  { id: "2020", name: "Cairo Santos", pos: "K", team: "CHI", bye: 10, adp: 164.3, inj: "" },
  { id: "5870", name: "Daniel Jones", pos: "QB", team: "IND", bye: 13, adp: 164.8, inj: "" },
  { id: "5844", name: "T.J. Hockenson", pos: "TE", team: "MIN", bye: 6, adp: 165.0, inj: "" },
  { id: "13305", name: "Mike Washington Jr.", pos: "RB", team: "LV", bye: 13, adp: 165.1, inj: "" },
  { id: "9758", name: "C.J. Stroud", pos: "QB", team: "HOU", bye: 8, adp: 165.4, inj: "" },
  { id: "5189", name: "Eddy Piñeiro", pos: "K", team: "SF", bye: 8, adp: 165.8, inj: "" },
  { id: "12467", name: "Jordan James", pos: "RB", team: "SF", bye: 8, adp: 165.9, inj: "Q" },
  { id: "9504", name: "Kayshon Boutte", pos: "WR", team: "NE", bye: 11, adp: 166.2, inj: "" },
  { id: "3678", name: "Wil Lutz", pos: "K", team: "DEN", bye: 10, adp: 166.2, inj: "" },
  { id: "9225", name: "Tank Bigsby", pos: "RB", team: "PHI", bye: 10, adp: 166.7, inj: "" },
  { id: "8210", name: "Chig Okonkwo", pos: "TE", team: "WAS", bye: 7, adp: 167.6, inj: "" },
  { id: "12492", name: "Pat Bryant", pos: "WR", team: "DEN", bye: 10, adp: 168.3, inj: "" },
  { id: "7002", name: "Juwan Johnson", pos: "TE", team: "NO", bye: 8, adp: 168.4, inj: "" },
  { id: "TEN", name: "Tennessee Defense", pos: "DST", team: "TEN", bye: 9, adp: 168.5, inj: "" },
  { id: "11581", name: "MarShawn Lloyd", pos: "RB", team: "GB", bye: 11, adp: 168.9, inj: "" },
  { id: "12535", name: "Isaac TeSlaa", pos: "WR", team: "DET", bye: 6, adp: 169.1, inj: "" },
  { id: "13330", name: "Kenyon Sadiq", pos: "TE", team: "NYJ", bye: 13, adp: 169.6, inj: "Q" },
  { id: "1945", name: "Chris Boswell", pos: "K", team: "PIT", bye: 9, adp: 169.9, inj: "" },
  { id: "8154", name: "Brian Robinson", pos: "RB", team: "ATL", bye: 11, adp: 170.6, inj: "" },
  { id: "4227", name: "Harrison Butker", pos: "K", team: "KC", bye: 5, adp: 171.2, inj: "" },
  { id: "7839", name: "Evan McPherson", pos: "K", team: "CIN", bye: 6, adp: 175.0, inj: "" },
  { id: "NO", name: "New Orleans Defense", pos: "DST", team: "NO", bye: 8, adp: 175.3, inj: "" },
  { id: "CLE", name: "Cleveland Defense", pos: "DST", team: "CLE", bye: 11, adp: 175.9, inj: "" },
  { id: "12469", name: "Dylan Sampson", pos: "RB", team: "CLE", bye: 11, adp: 178.3, inj: "" },
  { id: "12713", name: "Andy Borregales", pos: "K", team: "NE", bye: 11, adp: 179.6, inj: "" },
  { id: "ATL", name: "Atlanta Defense", pos: "DST", team: "ATL", bye: 11, adp: 182.7, inj: "" }
  ],

  "ppr": [
  { id: "9509", name: "Bijan Robinson", pos: "RB", team: "ATL", bye: 11, adp: 1.7, inj: "" },
  { id: "9221", name: "Jahmyr Gibbs", pos: "RB", team: "DET", bye: 6, adp: 1.8, inj: "" },
  { id: "9493", name: "Puka Nacua", pos: "WR", team: "LAR", bye: 11, adp: 3.1, inj: "Q" },
  { id: "7564", name: "Ja'Marr Chase", pos: "WR", team: "CIN", bye: 6, adp: 3.9, inj: "" },
  { id: "9488", name: "Jaxon Smith-Njigba", pos: "WR", team: "SEA", bye: 11, adp: 5.4, inj: "" },
  { id: "4034", name: "Christian McCaffrey", pos: "RB", team: "SF", bye: 8, adp: 6.3, inj: "Q" },
  { id: "7547", name: "Amon-Ra St. Brown", pos: "WR", team: "DET", bye: 6, adp: 6.7, inj: "" },
  { id: "6813", name: "Jonathan Taylor", pos: "RB", team: "IND", bye: 13, adp: 7.4, inj: "" },
  { id: "8112", name: "Drake London", pos: "WR", team: "ATL", bye: 11, adp: 10.2, inj: "" },
  { id: "9226", name: "De'Von Achane", pos: "RB", team: "MIA", bye: 6, adp: 10.3, inj: "" },
  { id: "6786", name: "CeeDee Lamb", pos: "WR", team: "DAL", bye: 14, adp: 10.9, inj: "" },
  { id: "8138", name: "James Cook III", pos: "RB", team: "BUF", bye: 7, adp: 13.3, inj: "" },
  { id: "9224", name: "Chase Brown", pos: "RB", team: "CIN", bye: 6, adp: 13.3, inj: "" },
  { id: "6794", name: "Justin Jefferson", pos: "WR", team: "MIN", bye: 6, adp: 13.5, inj: "" },
  { id: "10229", name: "Rashee Rice", pos: "WR", team: "KC", bye: 5, adp: 13.9, inj: "" },
  { id: "12527", name: "Ashton Jeanty", pos: "RB", team: "LV", bye: 13, adp: 14.6, inj: "" },
  { id: "3198", name: "Derrick Henry", pos: "RB", team: "BAL", bye: 13, adp: 16.9, inj: "" },
  { id: "5859", name: "A.J. Brown", pos: "WR", team: "NE", bye: 11, adp: 17.2, inj: "" },
  { id: "4866", name: "Saquon Barkley", pos: "RB", team: "PHI", bye: 10, adp: 20.1, inj: "" },
  { id: "8137", name: "George Pickens", pos: "WR", team: "DAL", bye: 14, adp: 20.2, inj: "" },
  { id: "12507", name: "Omarion Hampton", pos: "RB", team: "LAC", bye: 7, adp: 20.3, inj: "" },
  { id: "8144", name: "Chris Olave", pos: "WR", team: "NO", bye: 8, adp: 21.8, inj: "" },
  { id: "7569", name: "Nico Collins", pos: "WR", team: "HOU", bye: 8, adp: 22.6, inj: "" },
  { id: "8151", name: "Kenneth Walker", pos: "RB", team: "KC", bye: 5, adp: 24.8, inj: "" },
  { id: "9997", name: "Zay Flowers", pos: "WR", team: "BAL", bye: 13, adp: 25.2, inj: "" },
  { id: "8146", name: "Garrett Wilson", pos: "WR", team: "NYJ", bye: 13, adp: 28.1, inj: "" },
  { id: "8155", name: "Breece Hall", pos: "RB", team: "NYJ", bye: 13, adp: 28.3, inj: "" },
  { id: "7525", name: "DeVonta Smith", pos: "WR", team: "PHI", bye: 10, adp: 28.6, inj: "Q" },
  { id: "5850", name: "Josh Jacobs", pos: "RB", team: "GB", bye: 11, adp: 28.8, inj: "Q" },
  { id: "13287", name: "Jeremiyah Love", pos: "RB", team: "ARI", bye: 14, adp: 29.0, inj: "Q" },
  { id: "11632", name: "Malik Nabers", pos: "WR", team: "NYG", bye: 8, adp: 29.0, inj: "Q" },
  { id: "4984", name: "Josh Allen", pos: "QB", team: "BUF", bye: 7, adp: 29.2, inj: "" },
  { id: "8130", name: "Trey McBride", pos: "TE", team: "ARI", bye: 14, adp: 32.7, inj: "" },
  { id: "8150", name: "Kyren Williams", pos: "RB", team: "LAR", bye: 11, adp: 32.8, inj: "" },
  { id: "12481", name: "Cam Skattebo", pos: "RB", team: "NYG", bye: 8, adp: 33.4, inj: "" },
  { id: "12526", name: "Tetairoa McMillan", pos: "WR", team: "CAR", bye: 5, adp: 33.7, inj: "" },
  { id: "6801", name: "Tee Higgins", pos: "WR", team: "CIN", bye: 6, adp: 36.7, inj: "" },
  { id: "12514", name: "Emeka Egbuka", pos: "WR", team: "TB", bye: 10, adp: 37.1, inj: "Q" },
  { id: "7588", name: "Javonte Williams", pos: "RB", team: "DAL", bye: 14, adp: 37.2, inj: "" },
  { id: "11604", name: "Brock Bowers", pos: "TE", team: "LV", bye: 13, adp: 38.8, inj: "" },
  { id: "2133", name: "Davante Adams", pos: "WR", team: "LAR", bye: 11, adp: 41.0, inj: "" },
  { id: "11635", name: "Ladd McConkey", pos: "WR", team: "LAC", bye: 7, adp: 41.2, inj: "" },
  { id: "7543", name: "Travis Etienne Jr.", pos: "RB", team: "NO", bye: 8, adp: 41.2, inj: "" },
  { id: "8148", name: "Jameson Williams", pos: "WR", team: "DET", bye: 6, adp: 44.4, inj: "" },
  { id: "11584", name: "Bucky Irving", pos: "RB", team: "TB", bye: 10, adp: 45.0, inj: "" },
  { id: "5927", name: "Terry McLaurin", pos: "WR", team: "WAS", bye: 7, adp: 45.1, inj: "" },
  { id: "6790", name: "D'Andre Swift", pos: "RB", team: "CHI", bye: 10, adp: 45.7, inj: "" },
  { id: "7526", name: "Jaylen Waddle", pos: "WR", team: "DEN", bye: 10, adp: 46.2, inj: "Q" },
  { id: "11620", name: "Rome Odunze", pos: "WR", team: "CHI", bye: 10, adp: 49.1, inj: "" },
  { id: "11564", name: "Drake Maye", pos: "QB", team: "NE", bye: 11, adp: 50.0, inj: "" },
  { id: "12512", name: "Quinshon Judkins", pos: "RB", team: "CLE", bye: 11, adp: 51.2, inj: "" },
  { id: "4983", name: "DJ Moore", pos: "WR", team: "BUF", bye: 7, adp: 51.4, inj: "Q" },
  { id: "12490", name: "Bhayshul Tuten", pos: "RB", team: "JAX", bye: 7, adp: 54.2, inj: "" },
  { id: "4881", name: "Lamar Jackson", pos: "QB", team: "BAL", bye: 13, adp: 55.1, inj: "" },
  { id: "2216", name: "Mike Evans", pos: "WR", team: "SF", bye: 8, adp: 55.8, inj: "" },
  { id: "6770", name: "Joe Burrow", pos: "QB", team: "CIN", bye: 6, adp: 56.1, inj: "" },
  { id: "12519", name: "Luther Burden III", pos: "WR", team: "CHI", bye: 10, adp: 57.1, inj: "Q" },
  { id: "8142", name: "Alec Pierce", pos: "WR", team: "IND", bye: 13, adp: 58.0, inj: "PUP" },
  { id: "12517", name: "Colston Loveland", pos: "TE", team: "CHI", bye: 10, adp: 58.3, inj: "" },
  { id: "12529", name: "TreVeyon Henderson", pos: "RB", team: "NE", bye: 11, adp: 58.7, inj: "" },
  { id: "5045", name: "Courtland Sutton", pos: "WR", team: "DEN", bye: 10, adp: 60.5, inj: "" },
  { id: "5892", name: "David Montgomery", pos: "RB", team: "HOU", bye: 8, adp: 62.7, inj: "" },
  { id: "11628", name: "Marvin Harrison Jr.", pos: "WR", team: "ARI", bye: 14, adp: 64.6, inj: "" },
  { id: "12518", name: "Tyler Warren", pos: "TE", team: "IND", bye: 13, adp: 64.9, inj: "" },
  { id: "5846", name: "DK Metcalf", pos: "WR", team: "PIT", bye: 9, adp: 65.0, inj: "Q" },
  { id: "8167", name: "Christian Watson", pos: "WR", team: "GB", bye: 11, adp: 65.6, inj: "" },
  { id: "3294", name: "Dak Prescott", pos: "QB", team: "DAL", bye: 14, adp: 65.8, inj: "" },
  { id: "8228", name: "Jaylen Warren", pos: "RB", team: "PIT", bye: 9, adp: 66.1, inj: "" },
  { id: "5967", name: "Tony Pollard", pos: "RB", team: "TEN", bye: 9, adp: 67.1, inj: "" },
  { id: "9487", name: "Parker Washington", pos: "WR", team: "JAX", bye: 7, adp: 67.7, inj: "" },
  { id: "11566", name: "Jayden Daniels", pos: "QB", team: "WAS", bye: 7, adp: 71.5, inj: "" },
  { id: "7611", name: "Rhamondre Stevenson", pos: "RB", team: "NE", bye: 11, adp: 71.7, inj: "" },
  { id: "7021", name: "Rico Dowdle", pos: "RB", team: "PIT", bye: 9, adp: 72.3, inj: "" },
  { id: "6819", name: "Michael Pittman Jr.", pos: "WR", team: "PIT", bye: 9, adp: 73.2, inj: "Q" },
  { id: "7594", name: "Chuba Hubbard", pos: "RB", team: "CAR", bye: 5, adp: 74.6, inj: "Q" },
  { id: "13279", name: "Carnell Tate", pos: "WR", team: "TEN", bye: 9, adp: 75.1, inj: "" },
  { id: "11631", name: "Brian Thomas Jr.", pos: "WR", team: "JAX", bye: 7, adp: 75.1, inj: "" },
  { id: "7553", name: "Kyle Pitts Sr.", pos: "TE", team: "ATL", bye: 11, adp: 77.7, inj: "" },
  { id: "6904", name: "Jalen Hurts", pos: "QB", team: "PHI", bye: 10, adp: 78.0, inj: "" },
  { id: "13286", name: "Jadarian Price", pos: "RB", team: "SEA", bye: 11, adp: 78.0, inj: "Q" },
  { id: "8126", name: "Wan'Dale Robinson", pos: "WR", team: "TEN", bye: 9, adp: 79.5, inj: "" },
  { id: "12506", name: "Harold Fannin Jr.", pos: "TE", team: "CLE", bye: 11, adp: 79.5, inj: "" },
  { id: "421", name: "Matthew Stafford", pos: "QB", team: "LAR", bye: 11, adp: 82.2, inj: "" },
  { id: "5947", name: "Jakobi Meyers", pos: "WR", team: "JAX", bye: 7, adp: 82.3, inj: "" },
  { id: "10232", name: "Michael Wilson", pos: "WR", team: "ARI", bye: 14, adp: 82.7, inj: "" },
  { id: "12489", name: "RJ Harvey", pos: "RB", team: "DEN", bye: 10, adp: 83.6, inj: "" },
  { id: "8183", name: "Brock Purdy", pos: "QB", team: "SF", bye: 8, adp: 85.5, inj: "" },
  { id: "4037", name: "Chris Godwin Jr.", pos: "WR", team: "TB", bye: 10, adp: 85.8, inj: "" },
  { id: "9500", name: "Josh Downs", pos: "WR", team: "IND", bye: 13, adp: 85.8, inj: "Q" },
  { id: "10859", name: "Sam LaPorta", pos: "TE", team: "DET", bye: 6, adp: 87.4, inj: "" },
  { id: "7567", name: "Kenny Gainwell", pos: "RB", team: "TB", bye: 10, adp: 88.6, inj: "" },
  { id: "DEN", name: "Denver Defense", pos: "DST", team: "DEN", bye: 10, adp: 90.6, inj: "" },
  { id: "7523", name: "Trevor Lawrence", pos: "QB", team: "JAX", bye: 7, adp: 91.3, inj: "" },
  { id: "13281", name: "Jordyn Tyson", pos: "WR", team: "NO", bye: 8, adp: 92.4, inj: "Q" },
  { id: "2449", name: "Stefon Diggs", pos: "WR", team: "WAS", bye: 7, adp: 93.3, inj: "" },
  { id: "9754", name: "Quentin Johnston", pos: "WR", team: "LAC", bye: 7, adp: 93.5, inj: "" },
  { id: "SEA", name: "Seattle Defense", pos: "DST", team: "SEA", bye: 11, adp: 94.5, inj: "" },
  { id: "10222", name: "Jayden Reed", pos: "WR", team: "GB", bye: 11, adp: 94.6, inj: "" },
  { id: "6806", name: "J.K. Dobbins", pos: "RB", team: "DEN", bye: 10, adp: 96.6, inj: "Q" },
  { id: "4199", name: "Aaron Jones Sr.", pos: "RB", team: "MIN", bye: 6, adp: 97.5, inj: "" },
  { id: "11560", name: "Caleb Williams", pos: "QB", team: "CHI", bye: 10, adp: 98.5, inj: "" },
  { id: "4046", name: "Patrick Mahomes", pos: "QB", team: "KC", bye: 5, adp: 99.1, inj: "Q" },
  { id: "8134", name: "Khalil Shakir", pos: "WR", team: "BUF", bye: 7, adp: 100.5, inj: "" },
  { id: "9756", name: "Jordan Addison", pos: "WR", team: "MIN", bye: 6, adp: 101.4, inj: "" },
  { id: "HOU", name: "Houston Defense", pos: "DST", team: "HOU", bye: 8, adp: 102.3, inj: "" },
  { id: "9484", name: "Tucker Kraft", pos: "TE", team: "GB", bye: 11, adp: 103.5, inj: "Q" },
  { id: "8136", name: "Rachaad White", pos: "RB", team: "WAS", bye: 7, adp: 104.3, inj: "" },
  { id: "6797", name: "Justin Herbert", pos: "QB", team: "LAC", bye: 7, adp: 104.9, inj: "" },
  { id: "5872", name: "Deebo Samuel Sr.", pos: "WR", team: "SF", bye: 8, adp: 106.0, inj: "" },
  { id: "11624", name: "Xavier Worthy", pos: "WR", team: "KC", bye: 5, adp: 106.5, inj: "Q" },
  { id: "3163", name: "Jared Goff", pos: "QB", team: "DET", bye: 6, adp: 107.1, inj: "" },
  { id: "12508", name: "Jaxson Dart", pos: "QB", team: "NYG", bye: 8, adp: 107.9, inj: "" },
  { id: "1466", name: "Travis Kelce", pos: "TE", team: "KC", bye: 5, adp: 108.4, inj: "" },
  { id: "11583", name: "Jonathon Brooks", pos: "RB", team: "CAR", bye: 5, adp: 108.9, inj: "" },
  { id: "12534", name: "Kyle Monangai", pos: "RB", team: "CHI", bye: 10, adp: 109.5, inj: "" },
  { id: "13294", name: "Makai Lemon", pos: "WR", team: "PHI", bye: 10, adp: 110.4, inj: "Q" },
  { id: "11638", name: "Ricky Pearsall", pos: "WR", team: "SF", bye: 8, adp: 112.2, inj: "IR" },
  { id: "8121", name: "Romeo Doubs", pos: "WR", team: "NE", bye: 11, adp: 112.6, inj: "" },
  { id: "12533", name: "Jacory Croskey-Merritt", pos: "RB", team: "WAS", bye: 7, adp: 113.6, inj: "" },
  { id: "4217", name: "George Kittle", pos: "TE", team: "SF", bye: 8, adp: 113.9, inj: "PUP" },
  { id: "5022", name: "Dallas Goedert", pos: "TE", team: "PHI", bye: 10, adp: 115.7, inj: "" },
  { id: "MIN", name: "Minnesota Defense", pos: "DST", team: "MIN", bye: 6, adp: 115.8, inj: "" },
  { id: "11563", name: "Bo Nix", pos: "QB", team: "DEN", bye: 10, adp: 118.9, inj: "" },
  { id: "12501", name: "Matthew Golden", pos: "WR", team: "GB", bye: 11, adp: 118.9, inj: "" },
  { id: "8147", name: "John Metchie III", pos: "WR", team: "CAR", bye: 5, adp: 122.0, inj: "" },
  { id: "LAR", name: "LA Rams Defense", pos: "DST", team: "LAR", bye: 11, adp: 122.5, inj: "" },
  { id: "11586", name: "Blake Corum", pos: "RB", team: "LAR", bye: 11, adp: 123.4, inj: "" },
  { id: "8408", name: "Jordan Mason", pos: "RB", team: "MIN", bye: 6, adp: 123.4, inj: "" },
  { id: "11646", name: "Jalen Coker", pos: "WR", team: "CAR", bye: 5, adp: 124.3, inj: "" },
  { id: "8676", name: "Rashid Shaheed", pos: "WR", team: "SEA", bye: 11, adp: 126.9, inj: "" },
  { id: "13298", name: "KC Concepcion", pos: "WR", team: "CLE", bye: 11, adp: 127.9, inj: "" },
  { id: "NE", name: "New England Defense", pos: "DST", team: "NE", bye: 11, adp: 129.4, inj: "" },
  { id: "4892", name: "Baker Mayfield", pos: "QB", team: "TB", bye: 10, adp: 129.4, inj: "" },
  { id: "PHI", name: "Philadelphia Defense", pos: "DST", team: "PHI", bye: 10, adp: 129.9, inj: "" },
  { id: "11533", name: "Brandon Aubrey", pos: "K", team: "DAL", bye: 14, adp: 130.4, inj: "" },
  { id: "12484", name: "Jayden Higgins", pos: "WR", team: "HOU", bye: 8, adp: 130.7, inj: "" },
  { id: "DET", name: "Detroit Defense", pos: "DST", team: "DET", bye: 6, adp: 131.6, inj: "" },
  { id: "9508", name: "Tyjae Spears", pos: "RB", team: "TEN", bye: 9, adp: 132.2, inj: "" },
  { id: "10213", name: "Tre Tucker", pos: "WR", team: "LV", bye: 13, adp: 133.0, inj: "" },
  { id: "6783", name: "Jerry Jeudy", pos: "WR", team: "CLE", bye: 11, adp: 133.9, inj: "" },
  { id: "8131", name: "Isaiah Likely", pos: "TE", team: "NYG", bye: 8, adp: 134.4, inj: "" },
  { id: "8110", name: "Jake Ferguson", pos: "TE", team: "DAL", bye: 14, adp: 135.9, inj: "" },
  { id: "4981", name: "Calvin Ridley", pos: "WR", team: "TEN", bye: 9, adp: 135.9, inj: "" },
  { id: "12545", name: "Tyler Shough", pos: "QB", team: "NO", bye: 8, adp: 136.9, inj: "" },
  { id: "5012", name: "Mark Andrews", pos: "TE", team: "BAL", bye: 13, adp: 137.8, inj: "" },
  { id: "2747", name: "Jason Myers", pos: "K", team: "SEA", bye: 11, adp: 139.2, inj: "" },
  { id: "12860", name: "Theo Wease Jr.", pos: "WR", team: "MIA", bye: 6, adp: 139.7, inj: "" },
  { id: "9753", name: "Zach Charbonnet", pos: "RB", team: "SEA", bye: 11, adp: 140.2, inj: "PUP" },
  { id: "5849", name: "Kyler Murray", pos: "QB", team: "MIN", bye: 6, adp: 140.8, inj: "" },
  { id: "3451", name: "Ka'imi Fairbairn", pos: "K", team: "HOU", bye: 8, adp: 141.6, inj: "" },
  { id: "4035", name: "Alvin Kamara", pos: "RB", team: "NO", bye: 8, adp: 142.2, inj: "" },
  { id: "4943", name: "Sam Darnold", pos: "QB", team: "SEA", bye: 11, adp: 143.6, inj: "" },
  { id: "PIT", name: "Pittsburgh Defense", pos: "DST", team: "PIT", bye: 9, adp: 143.8, inj: "" },
  { id: "8259", name: "Cameron Dicker", pos: "K", team: "LAC", bye: 7, adp: 144.7, inj: "" },
  { id: "6804", name: "Jordan Love", pos: "QB", team: "GB", bye: 11, adp: 144.8, inj: "" },
  { id: "7049", name: "Jauan Jennings", pos: "WR", team: "MIN", bye: 6, adp: 144.8, inj: "" },
  { id: "LAC", name: "LA Chargers Defense", pos: "DST", team: "LAC", bye: 7, adp: 144.9, inj: "" },
  { id: "11618", name: "Jalen McMillan", pos: "WR", team: "TB", bye: 10, adp: 145.0, inj: "Q" },
  { id: "12540", name: "Chimere Dike", pos: "WR", team: "TEN", bye: 9, adp: 145.7, inj: "" },
  { id: "SF", name: "San Francisco Defense", pos: "DST", team: "SF", bye: 8, adp: 145.7, inj: "" },
  { id: "12492", name: "Pat Bryant", pos: "WR", team: "DEN", bye: 10, adp: 147.1, inj: "" },
  { id: "13305", name: "Mike Washington Jr.", pos: "RB", team: "LV", bye: 13, adp: 147.8, inj: "" },
  { id: "7571", name: "Rashod Bateman", pos: "WR", team: "BAL", bye: 13, adp: 147.9, inj: "" },
  { id: "13346", name: "Denzel Boston", pos: "WR", team: "CLE", bye: 11, adp: 148.0, inj: "" },
  { id: "13345", name: "Jonah Coleman", pos: "RB", team: "DEN", bye: 10, adp: 148.2, inj: "" },
  { id: "11539", name: "Jake Bates", pos: "K", team: "DET", bye: 6, adp: 149.6, inj: "" },
  { id: "12493", name: "Oronde Gadsden", pos: "TE", team: "LAC", bye: 7, adp: 149.8, inj: "" },
  { id: "12474", name: "Woody Marks", pos: "RB", team: "HOU", bye: 8, adp: 150.7, inj: "" },
  { id: "13414", name: "Kaelon Black", pos: "RB", team: "SF", bye: 8, adp: 150.8, inj: "Q" },
  { id: "9502", name: "Tank Dell", pos: "WR", team: "HOU", bye: 8, adp: 151.3, inj: "Q" },
  { id: "12015", name: "Harrison Mevis", pos: "K", team: "LAR", bye: 11, adp: 151.7, inj: "" },
  { id: "5870", name: "Daniel Jones", pos: "QB", team: "IND", bye: 13, adp: 152.4, inj: "" },
  { id: "10236", name: "Dalton Kincaid", pos: "TE", team: "BUF", bye: 7, adp: 152.5, inj: "" },
  { id: "13417", name: "De'Zhaun Stribling", pos: "WR", team: "SF", bye: 8, adp: 152.5, inj: "" },
  { id: "8205", name: "Isiah Pacheco", pos: "RB", team: "DET", bye: 6, adp: 152.5, inj: "Q" },
  { id: "11655", name: "Tyrone Tracy Jr.", pos: "RB", team: "NYG", bye: 8, adp: 152.7, inj: "" },
  { id: "11610", name: "Malik Washington", pos: "WR", team: "MIA", bye: 6, adp: 154.1, inj: "" },
  { id: "JAX", name: "Jacksonville Defense", pos: "DST", team: "JAX", bye: 7, adp: 154.3, inj: "" },
  { id: "8180", name: "Jalen Nailor", pos: "WR", team: "LV", bye: 13, adp: 155.3, inj: "" },
  { id: "11647", name: "Kimani Vidal", pos: "RB", team: "LAC", bye: 7, adp: 155.5, inj: "" },
  { id: "5001", name: "Dalton Schultz", pos: "TE", team: "HOU", bye: 8, adp: 155.5, inj: "" },
  { id: "650", name: "Nick Folk", pos: "K", team: "ATL", bye: 11, adp: 155.6, inj: "" },
  { id: "11576", name: "Braelon Allen", pos: "RB", team: "NYJ", bye: 13, adp: 155.7, inj: "" },
  { id: "NYJ", name: "NY Jets Defense", pos: "DST", team: "NYJ", bye: 13, adp: 155.9, inj: "" },
  { id: "6650", name: "Chase McLaughlin", pos: "K", team: "TB", bye: 10, adp: 156.5, inj: "" },
  { id: "11792", name: "Will Reichard", pos: "K", team: "MIN", bye: 6, adp: 156.5, inj: "" },
  { id: "11581", name: "MarShawn Lloyd", pos: "RB", team: "GB", bye: 11, adp: 156.6, inj: "" },
  { id: "4039", name: "Cooper Kupp", pos: "WR", team: "SEA", bye: 11, adp: 157.7, inj: "" },
  { id: "11786", name: "Cam Little", pos: "K", team: "JAX", bye: 7, adp: 158.1, inj: "" },
  { id: "1945", name: "Chris Boswell", pos: "K", team: "PIT", bye: 9, adp: 158.1, inj: "" },
  { id: "3214", name: "Hunter Henry", pos: "TE", team: "NE", bye: 11, adp: 158.5, inj: "" },
  { id: "7002", name: "Juwan Johnson", pos: "TE", team: "NO", bye: 8, adp: 158.8, inj: "" },
  { id: "13413", name: "Cyrus Allen", pos: "WR", team: "KC", bye: 5, adp: 158.8, inj: "" },
  { id: "12711", name: "Tyler Loop", pos: "K", team: "BAL", bye: 13, adp: 158.9, inj: "" },
  { id: "5189", name: "Eddy Piñeiro", pos: "K", team: "SF", bye: 8, adp: 159.1, inj: "" },
  { id: "11575", name: "Ray Davis", pos: "RB", team: "BUF", bye: 7, adp: 160.0, inj: "" },
  { id: "2020", name: "Cairo Santos", pos: "K", team: "CHI", bye: 10, adp: 160.3, inj: "" },
  { id: "9511", name: "Keaton Mitchell", pos: "RB", team: "LAC", bye: 7, adp: 160.3, inj: "" },
  { id: "BUF", name: "Buffalo Defense", pos: "DST", team: "BUF", bye: 7, adp: 160.3, inj: "" },
  { id: "GB", name: "Green Bay Defense", pos: "DST", team: "GB", bye: 11, adp: 160.4, inj: "" },
  { id: "11625", name: "Adonai Mitchell", pos: "WR", team: "NYJ", bye: 13, adp: 160.5, inj: "" },
  { id: "TEN", name: "Tennessee Defense", pos: "DST", team: "TEN", bye: 9, adp: 160.6, inj: "" },
  { id: "12530", name: "Travis Hunter", pos: "WR", team: "JAX", bye: 7, adp: 160.8, inj: "" },
  { id: "9758", name: "C.J. Stroud", pos: "QB", team: "HOU", bye: 8, adp: 160.8, inj: "" },
  { id: "13293", name: "Ja'Kobi Lane", pos: "WR", team: "BAL", bye: 13, adp: 160.9, inj: "" },
  { id: "4227", name: "Harrison Butker", pos: "K", team: "KC", bye: 5, adp: 161.4, inj: "" },
  { id: "BAL", name: "Baltimore Defense", pos: "DST", team: "BAL", bye: 13, adp: 161.5, inj: "" },
  { id: "10219", name: "Chris Rodriguez Jr.", pos: "RB", team: "JAX", bye: 7, adp: 161.8, inj: "" },
  { id: "12509", name: "Tre' Harris", pos: "WR", team: "LAC", bye: 7, adp: 162.0, inj: "" },
  { id: "13276", name: "Omar Cooper Jr.", pos: "WR", team: "NYJ", bye: 13, adp: 162.2, inj: "" },
  { id: "11603", name: "AJ Barner", pos: "TE", team: "SEA", bye: 11, adp: 162.4, inj: "" },
  { id: "12469", name: "Dylan Sampson", pos: "RB", team: "CLE", bye: 11, adp: 162.4, inj: "" },
  { id: "8161", name: "Malik Willis", pos: "QB", team: "MIA", bye: 6, adp: 162.7, inj: "" },
  { id: "6039", name: "Ty Johnson", pos: "RB", team: "BUF", bye: 7, adp: 162.8, inj: "Q" },
  { id: "12467", name: "Jordan James", pos: "RB", team: "SF", bye: 8, adp: 163.1, inj: "Q" },
  { id: "8210", name: "Chig Okonkwo", pos: "TE", team: "WAS", bye: 7, adp: 163.3, inj: "" },
  { id: "9480", name: "Brenton Strange", pos: "TE", team: "JAX", bye: 7, adp: 163.5, inj: "" },
  { id: "13545", name: "Trey Smack", pos: "K", team: "GB", bye: 11, adp: 163.8, inj: "" },
  { id: "9225", name: "Tank Bigsby", pos: "RB", team: "PHI", bye: 10, adp: 164.8, inj: "" },
  { id: "8154", name: "Brian Robinson", pos: "RB", team: "ATL", bye: 11, adp: 164.8, inj: "" },
  { id: "13301", name: "Antonio Williams", pos: "WR", team: "WAS", bye: 7, adp: 164.9, inj: "" },
  { id: "3678", name: "Wil Lutz", pos: "K", team: "DEN", bye: 10, adp: 165.0, inj: "" },
  { id: "5995", name: "Justice Hill", pos: "RB", team: "BAL", bye: 13, adp: 165.1, inj: "" },
  { id: "5844", name: "T.J. Hockenson", pos: "TE", team: "MIN", bye: 6, adp: 165.7, inj: "" },
  { id: "8132", name: "Tyler Allgeier", pos: "RB", team: "ARI", bye: 14, adp: 165.7, inj: "" },
  { id: "12457", name: "Jaydon Blue", pos: "RB", team: "DAL", bye: 14, adp: 165.9, inj: "" },
  { id: "3257", name: "Jacoby Brissett", pos: "QB", team: "ARI", bye: 14, adp: 166.0, inj: "" },
  { id: "ATL", name: "Atlanta Defense", pos: "DST", team: "ATL", bye: 11, adp: 166.9, inj: "" },
  { id: "96", name: "Aaron Rodgers", pos: "QB", team: "PIT", bye: 9, adp: 167.3, inj: "" },
  { id: "13330", name: "Kenyon Sadiq", pos: "TE", team: "NYJ", bye: 13, adp: 167.3, inj: "Q" },
  { id: "13269", name: "Fernando Mendoza", pos: "QB", team: "LV", bye: 13, adp: 167.4, inj: "" },
  { id: "7042", name: "Tyler Bass", pos: "K", team: "BUF", bye: 7, adp: 167.8, inj: "" },
  { id: "8172", name: "Greg Dulcich", pos: "TE", team: "MIA", bye: 6, adp: 167.9, inj: "" },
  { id: "11199", name: "Emari Demercado", pos: "RB", team: "KC", bye: 5, adp: 168.2, inj: "" },
  { id: "8117", name: "Jalen Tolbert", pos: "WR", team: "MIA", bye: 6, adp: 168.7, inj: "" },
  { id: "DAL", name: "Dallas Defense", pos: "DST", team: "DAL", bye: 14, adp: 168.8, inj: "" },
  { id: "CLE", name: "Cleveland Defense", pos: "DST", team: "CLE", bye: 11, adp: 168.9, inj: "" },
  { id: "11783", name: "Ryan Flournoy", pos: "WR", team: "DAL", bye: 14, adp: 169.6, inj: "" },
  { id: "6149", name: "Darius Slayton", pos: "WR", team: "NYG", bye: 8, adp: 170.1, inj: "" },
  { id: "CHI", name: "Chicago Defense", pos: "DST", team: "CHI", bye: 10, adp: 170.6, inj: "" },
  { id: "9228", name: "Bryce Young", pos: "QB", team: "CAR", bye: 5, adp: 170.7, inj: "" },
  { id: "7839", name: "Evan McPherson", pos: "K", team: "CIN", bye: 6, adp: 171.3, inj: "" },
  { id: "NO", name: "New Orleans Defense", pos: "DST", team: "NO", bye: 8, adp: 171.4, inj: "" },
  { id: "12522", name: "Cam Ward", pos: "QB", team: "TEN", bye: 9, adp: 171.8, inj: "" },
  { id: "NYG", name: "NY Giants Defense", pos: "DST", team: "NYG", bye: 8, adp: 171.9, inj: "" },
  { id: "13320", name: "Zachariah Branch", pos: "WR", team: "ATL", bye: 11, adp: 172.0, inj: "" },
  { id: "13274", name: "Germie Bernard", pos: "WR", team: "PIT", bye: 9, adp: 172.4, inj: "" },
  { id: "9504", name: "Kayshon Boutte", pos: "WR", team: "NE", bye: 11, adp: 173.0, inj: "" },
  { id: "4137", name: "James Conner", pos: "RB", team: "ARI", bye: 14, adp: 173.2, inj: "Q" },
  { id: "11058", name: "Blake Grupe", pos: "K", team: "IND", bye: 13, adp: 173.5, inj: "" },
  { id: "4147", name: "Samaje Perine", pos: "RB", team: "CIN", bye: 6, adp: 173.7, inj: "" },
  { id: "9486", name: "Dontayvion Wicks", pos: "WR", team: "PHI", bye: 10, adp: 173.8, inj: "" },
  { id: "4950", name: "Christian Kirk", pos: "WR", team: "SF", bye: 8, adp: 175.7, inj: "Q" },
  { id: "KC", name: "Kansas City Defense", pos: "DST", team: "KC", bye: 5, adp: 177.8, inj: "" },
  { id: "12535", name: "Isaac TeSlaa", pos: "WR", team: "DET", bye: 6, adp: 177.9, inj: "" },
  { id: "7600", name: "Pat Freiermuth", pos: "TE", team: "PIT", bye: 9, adp: 178.2, inj: "" },
  { id: "CIN", name: "Cincinnati Defense", pos: "DST", team: "CIN", bye: 6, adp: 178.2, inj: "" },
  { id: "MIA", name: "Miami Defense", pos: "DST", team: "MIA", bye: 6, adp: 180.0, inj: "" },
  { id: "13296", name: "Caleb Douglas", pos: "WR", team: "MIA", bye: 6, adp: 184.5, inj: "" },
  { id: "WAS", name: "Washington Defense", pos: "DST", team: "WAS", bye: 7, adp: 187.0, inj: "" },
  { id: "7090", name: "Darnell Mooney", pos: "WR", team: "NYG", bye: 8, adp: 190.3, inj: "" }
  ]
};

// The Alpine default, and what the app falls back to if a set is missing.
const PLAYERS = ADP_SETS["half"];
